Repository keep-network/keep-core, pull requests merged in 2020-07, with the labels that each got.

#1832 Loading indicator for KEEP token dashboard
  solidity/dashboard/src/components/ChooseWallet.jsx
  solidity/dashboard/src/components/DelegationOverview.jsx
  solidity/dashboard/src/components/Icons.jsx
  solidity/dashboard/src/components/Loadable.jsx
  solidity/dashboard/src/components/OwnedTokensOverview.jsx
  solidity/dashboard/src/components/SlashedTokens.jsx
  solidity/dashboard/src/components/TokenGrantOverview.jsx
  solidity/dashboard/src/components/TokensOverview.jsx
  solidity/dashboard/src/components/skeletons/CircleSkeleton.jsx
  solidity/dashboard/src/components/skeletons/DataTableSkeleton.jsx
  solidity/dashboard/src/components/skeletons/DelegatedTokensSkeleton.jsx
  solidity/dashboard/src/components/skeletons/Skeleton.jsx
  solidity/dashboard/src/components/skeletons/TokenOverviewSkeleton.jsx
  solidity/dashboard/src/contexts/TokensPageContext.jsx
  solidity/dashboard/src/css/app.less
  solidity/dashboard/src/css/indicator.less
  solidity/dashboard/src/css/skeletons.less
  solidity/dashboard/src/css/vars.less
  solidity/dashboard/src/pages/KeepRandomBeaconApplicationPage.jsx
  solidity/dashboard/src/pages/OperatorPage.jsx
  solidity/dashboard/src/pages/TBTCApplicationPage.jsx
  solidity/dashboard/src/pages/TokenGrantsPage.jsx
  solidity/dashboard/src/pages/TokensPage.jsx
  solidity/dashboard/src/static/svg/keep-loading-indicator.svg
Labels: :old_key: token dashboard, process & client team

#1844 Consistent approach to empty states for tables
  solidity/dashboard/src/components/AuthorizationHistory.jsx
  solidity/dashboard/src/components/AuthorizeContracts.jsx
  solidity/dashboard/src/components/BondingSection.jsx
  solidity/dashboard/src/components/DataTable.jsx
  solidity/dashboard/src/components/DelegatedTokensTable.jsx
  solidity/dashboard/src/components/PendingUndelegation.jsx
  solidity/dashboard/src/components/RewardsGroups.jsx
  solidity/dashboard/src/components/SlashedTokensList.jsx
  solidity/dashboard/src/components/Tile.jsx
  solidity/dashboard/src/components/Undelegations.jsx
  solidity/dashboard/src/components/WithdrawalHistory.jsx
  solidity/dashboard/src/css/datatable.less
Labels: :old_key: token dashboard

#1845 Disable menu on the wallet page
  solidity/dashboard/src/components/SideMenu.jsx
  solidity/dashboard/src/components/SlashedTokens.jsx
  solidity/dashboard/src/css/app.less
  solidity/dashboard/src/static/svg/glossary.svg
  solidity/dashboard/src/static/svg/tokens.svg
Labels: :old_key: token dashboard

#1897 Update KEEP token dashboard for subscribing to `Staked` event
  solidity/dashboard/src/pages/TokensPageContainer.jsx
Labels: :old_key: token dashboard

#1847 Token overview page
  solidity/dashboard/src/components/DelegatedTokensTable.jsx
  solidity/dashboard/src/components/Header.jsx
  solidity/dashboard/src/components/LedgerModal.jsx
  solidity/dashboard/src/components/NetworkStatus.jsx
  solidity/dashboard/src/components/SideMenu.jsx
  solidity/dashboard/src/components/TokenOverview.jsx
  solidity/dashboard/src/components/Undelegations.jsx
  solidity/dashboard/src/css/buttons.less
  solidity/dashboard/src/css/network-status.less
  solidity/dashboard/src/css/tokens-context-switcher.less
  solidity/dashboard/src/css/tokens-page.less
  solidity/dashboard/src/pages/TokenOverviewPage.jsx
  solidity/dashboard/src/pages/TokensPageContainer.jsx
  solidity/dashboard/src/static/svg/grant-context-icon.svg
  solidity/dashboard/src/static/svg/money-wallet-open.svg
  solidity/dashboard/src/utils/arithmetics.utils.js
Labels: :old_key: token dashboard, process & client team

#1886 Fix React's warnings in web console
  solidity/dashboard/src/components/ChooseWallet.jsx
  solidity/dashboard/src/components/ChooseWalletAddress.jsx
  solidity/dashboard/src/components/skeletons/DataTableSkeleton.jsx
  solidity/dashboard/src/services/beacon-authorization.service.js
  solidity/dashboard/src/services/tbtc-authorization.service.js
  solidity/dashboard/src/services/token-staking.service.js
Labels: :old_key: token dashboard

#1857 Display a confirmation modal before undelegation or delegation in KEEP token dashboard
  solidity/dashboard/src/components/Button.jsx
  solidity/dashboard/src/components/ConfirmationModal.jsx
  solidity/dashboard/src/components/DelegateStakeForm.jsx
  solidity/dashboard/src/components/UndelegateStakeButton.jsx
  solidity/dashboard/src/hooks/useCustomOnSubmitFormik.js
  solidity/dashboard/src/pages/TokensPage.jsx
Labels: :old_key: token dashboard

#1858 Wallet page bug fixes
  solidity/dashboard/src/components/ChooseWallet.jsx
  solidity/dashboard/src/components/Web3ContextProvider.jsx
  solidity/dashboard/src/css/choose-wallet.less
Labels: :old_key: token dashboard

#1843 Random Beacon rewards page
  solidity/contracts/stubs/KeepRandomBeaconOperatorRewardsStub.sol
  solidity/dashboard/src/components/Icons.jsx
  solidity/dashboard/src/components/Rewards.jsx
  solidity/dashboard/src/components/RewardsGroups.jsx
  solidity/dashboard/src/components/RewardsStatus.jsx
  solidity/dashboard/src/components/StatusBadge.jsx
  solidity/dashboard/src/components/TokenAmount.jsx
  solidity/dashboard/src/components/WithdrawalHistory.jsx
  solidity/dashboard/src/constants/constants.js
  solidity/dashboard/src/css/commons.less
  solidity/dashboard/src/css/rewards.less
  solidity/dashboard/src/css/typography.less
  solidity/dashboard/src/pages/RewardsPage.jsx
  solidity/dashboard/src/pages/TokenGrantsPage.jsx
  solidity/dashboard/src/services/rewards.service.js
  solidity/dashboard/src/services/token-staking.service.js
  solidity/dashboard/src/static/svg/eth.svg
  solidity/scripts/rewards.js
Labels: :old_key: token dashboard

#1861 Support viewing grants by ID without a paired wallet
  solidity/dashboard/src/components/Routing.jsx
  solidity/dashboard/src/components/TokenGrantOverview.jsx
  solidity/dashboard/src/contracts.js
  solidity/dashboard/src/hooks/useFetchData.js
  solidity/dashboard/src/pages/TokenGrantPreviewPage.jsx
  solidity/dashboard/src/services/token-grants.service.js
Labels: :old_key: token dashboard

#1907 Fix a ledger bug
  solidity/dashboard/src/connectors/ledger.js
Labels: :old_key: token dashboard

#1893 Stake top-ups
  solidity/contracts/TokenStaking.sol
  solidity/contracts/libraries/staking/GrantStaking.sol
  solidity/contracts/libraries/staking/TopUps.sol
  solidity/migrations/2_deploy_contracts.js
  solidity/test/helpers/delegateStake.js
  solidity/test/helpers/initContracts.js
  solidity/test/token_grant/TestTokenGrantStake.js
  solidity/test/token_stake/TestTokenStake.js
  solidity/test/token_stake/TestTopUps.js
Labels: process & client team, ⛓chain

#1902 Reduce bytecode size of TokenStaking contract
  solidity/contracts/Authorizations.sol
  solidity/contracts/TokenStaking.sol
  solidity/contracts/libraries/staking/TopUps.sol
  solidity/contracts/stubs/TokenStakingSlashingStub.sol
  solidity/contracts/stubs/TokenStakingStub.sol
  solidity/migrations/2_deploy_contracts.js
  solidity/test/RolesLookupTest.js
  solidity/test/helpers/initContracts.js
  solidity/test/token_grant/TestManagedGrant.js
  solidity/test/token_grant/TestManagedGrantFactory.js
  solidity/test/token_grant/TestStakingPolicy.js
  solidity/test/token_grant/TestTokenGrant.js
  solidity/test/token_grant/TestTokenGrantRevoke.js
  solidity/test/token_grant/TestTokenGrantStake.js
  solidity/test/token_grant/TestTokenGrantWithdraw.js
  solidity/test/token_stake/TestDelegatedAuthority.js
  solidity/test/token_stake/TestMinimumStake.js
  solidity/test/token_stake/TestPunishment.js
  solidity/test/token_stake/TestStakingGrant.js
  solidity/test/token_stake/TestTokenStake.js
  solidity/test/token_stake/TestTokenStakeLock.js
  solidity/test/token_stake/TestTopUps.js
Labels: ⛓chain

#1924 Make sure only KEEP token can call escrow's receiveApproval
  solidity/contracts/TokenStakingEscrow.sol
  solidity/test/token_stake/TestTokenStakingEscrow.js
Labels: ⛓chain

#1921 Respect redelegated tokens when migrating between escrows
  solidity/contracts/TokenStakingEscrow.sol
  solidity/test/token_stake/TestTokenStakingEscrow.js
Labels: ⛓chain

#1914 Increased gas price ceiling to 60Gwei
  solidity/contracts/KeepRandomBeaconOperator.sol
  solidity/test/random_beacon_operator/TestPublishDkgResult.js
  solidity/test/random_beacon_service/TestRelayRequestCallback.js
Labels: ⛓chain

#1920 Move test values to a new file
  solidity/test/TestRewards.js
  solidity/test/helpers/rewardsData.js
Labels: ⛓chain

#1906 Allow bridging already-staked tokens on new staking contract
  solidity/contracts/StakingPortBacker.sol
  solidity/contracts/TokenStaking.sol
  solidity/contracts/libraries/RolesLookup.sol
  solidity/contracts/libraries/staking/GrantStaking.sol
  solidity/contracts/stubs/TokenStakingStub.sol
  solidity/test/random_beacon_operator/TestSlashing.js
  solidity/test/token_stake/TestMultipleStakingContracts.js
  solidity/test/token_stake/TestStakingPortBacker.js
  solidity/test/token_stake/TestTokenStake.js
Labels: ⛓chain

#1915 Undelegation period set to two weeks for the first two months after TokenStaking deployment
  solidity/contracts/TokenStaking.sol
  solidity/test/token_stake/TestTokenStake.js
Labels: ⛓chain

#1933 Fix total balance of grants- KEEP token dashboard overview page
  solidity/dashboard/src/components/ChooseWallet.jsx
  solidity/dashboard/src/pages/TokenGrantsPage.jsx
  solidity/dashboard/src/pages/TokenOverviewPage.jsx
  solidity/dashboard/src/reducers/tokens-page.reducer.js
  solidity/dashboard/src/services/tokens-page.service.js
Labels: :old_key: token dashboard

#1929 Allow to top-up a stake during initialization period
  solidity/contracts/TokenStaking.sol
  solidity/contracts/stubs/OperatorParamsStub.sol
  solidity/contracts/utils/OperatorParams.sol
  solidity/test/TestOperatorParams.js
  solidity/test/token_stake/TestTokenStake.js
  solidity/test/token_stake/TestTopUps.js
Labels: ⛓chain

#1935 Get operator contract ready for rewards, for real this time
  solidity/contracts/KeepRandomBeaconOperator.sol
  solidity/contracts/libraries/operator/Groups.sol
Labels: process & client team, ⛓chain

#1938 Respect redelegated tokens when withdrawing revoked grant from escrow
  solidity/contracts/TokenStakingEscrow.sol
  solidity/test/token_stake/TestTokenStakingEscrow.js
Labels: ⛓chain

#1940 TokenStakingEscrow reverts if it already has a deposit
  solidity/contracts/TokenStakingEscrow.sol
  solidity/test/token_stake/TestStakingGrant.js
Labels: ⛓chain

#1919 Fix for not presenting slashes
  solidity/dashboard/src/services/slashed-tokens.service.js
Labels: :old_key: token dashboard

#1928 Update KEEP token dashboard for TokenStakingEscrow
  solidity/dashboard/src/components/DelegationOverview.jsx
  solidity/dashboard/src/components/RecoverStakeButton.jsx
  solidity/dashboard/src/components/TokenGrantOverview.jsx
  solidity/dashboard/src/components/UndelegateStakeButton.jsx
  solidity/dashboard/src/constants/constants.js
  solidity/dashboard/src/contexts/TokensPageContext.jsx
  solidity/dashboard/src/contracts.js
  solidity/dashboard/src/pages/TokenGrantsPage.jsx
  solidity/dashboard/src/pages/TokenOverviewPage.jsx
  solidity/dashboard/src/pages/TokensPageContainer.jsx
  solidity/dashboard/src/reducers/tokens-page.reducer.js
  solidity/dashboard/src/services/token-grants.service.js
  solidity/dashboard/src/services/token-staking-escrow.service.js
Labels: :old_key: token dashboard, process & client team

#1951 Added DepositRedelegated event to TokenStakingEscrow
  solidity/contracts/TokenStakingEscrow.sol
  solidity/test/token_stake/TestStakingGrant.js
Labels: ⛓chain

#1949 Do not allow to redelegate to an operator from which a delegation has been cancelled
  solidity/contracts/TokenStaking.sol
  solidity/contracts/TokenStakingEscrow.sol
  solidity/contracts/libraries/staking/TopUps.sol
  solidity/test/token_grant/TestTokenGrantStake.js
  solidity/test/token_stake/TestStakingGrant.js
  solidity/test/token_stake/TestTokenStakingEscrow.js
Labels: process & client team, ⛓chain

#1950 Added test cases for escrow redelegations undelegated/cancelled
  solidity/test/token_stake/TestStakingGrant.js
Labels: ⛓chain
