Repository keep-network/keep-core, pull requests merged in 2020-10, with the labels that each got.

#2105 Fund properly before allocating rewards
  solidity/contracts/Rewards.sol
  solidity/test/rewards/TestBeaconBackportRewards.js
  solidity/test/rewards/TestBeaconRewards.js
  solidity/test/rewards/TestRewards.js
Labels: ⛓chain

#2073 Loading wrappers
  solidity/dashboard/src/components/TokensContextSwitcher.jsx
  solidity/dashboard/src/components/skeletons/CardSkeleton.jsx
  solidity/dashboard/src/components/skeletons/TokenAmountSkeleton.jsx
  solidity/dashboard/src/components/skeletons/TokenBalancesOverviewSkeleton.jsx
  solidity/dashboard/src/pages/TokenOverviewPage.jsx
Labels: :old_key: token dashboard

#2050 Format ETH amount on the Rewards page
  solidity/dashboard/src/components/Rewards.jsx
  solidity/dashboard/src/components/TokenAmount.jsx
  solidity/dashboard/src/css/commons.less
  solidity/dashboard/src/css/tooltip.less
  solidity/dashboard/src/services/rewards.service.js
  solidity/dashboard/src/static/svg/eth.svg
  solidity/dashboard/src/utils/ethereum.utils.js
Labels: :old_key: token dashboard

#2108 Make rewards upgradeable
  solidity/contracts/Rewards.sol
  solidity/contracts/stubs/NewRewardsStub.sol
  solidity/test/rewards/TestRewardUpgrades.js
Labels: ⛓chain

#2109 Disabling bootstrap-2.core.keep.test.boar.network
  docs/run-random-beacon.adoc
Labels: :book: documentation, :cloud: infrastructure

#2096 Main nav update
  solidity/dashboard/.env
  solidity/dashboard/.gitignore
  solidity/dashboard/src/App.js
  solidity/dashboard/src/components/Footer.jsx
  solidity/dashboard/src/components/Icons.jsx
  solidity/dashboard/src/components/SideMenu.jsx
  solidity/dashboard/src/css/app.less
  solidity/dashboard/src/css/footer.less
  solidity/dashboard/src/css/side-menu.less
  solidity/dashboard/src/static/svg/authorize.svg
  solidity/dashboard/src/static/svg/beacon.svg
  solidity/dashboard/src/static/svg/fees-vector.svg
  solidity/dashboard/src/static/svg/glossary.svg
  solidity/dashboard/src/static/svg/home.svg
  solidity/dashboard/src/static/svg/question.svg
  solidity/dashboard/src/static/svg/rewards.svg
Labels: :old_key: token dashboard

#2098 Rename `glossary` to `resources`
  solidity/dashboard/src/components/Routing.jsx
  solidity/dashboard/src/components/SideMenu.jsx
  solidity/dashboard/src/components/glossary/Navigation.jsx
  solidity/dashboard/src/components/resources/DelegationDiagram.jsx
  solidity/dashboard/src/components/resources/DocumentationSection.jsx
  solidity/dashboard/src/components/resources/Navigation.jsx
  solidity/dashboard/src/components/resources/TerminologyDataTable.jsx
  solidity/dashboard/src/css/app.less
  solidity/dashboard/src/css/resources-page.less
  solidity/dashboard/src/pages/GlossaryPage.jsx
  solidity/dashboard/src/pages/ResourcesPage.jsx
Labels: :old_key: token dashboard

#2114 Make sure upgrade initiated interval ends before finalizing the upgrade
  solidity/contracts/Rewards.sol
  solidity/test/rewards/TestRewardUpgrades.js
Labels: ⛓chain

#2115 Dragons and invariants: Do not decrease dispensed rewards on finalizing upgrade
  solidity/contracts/Rewards.sol
  solidity/test/rewards/TestRewardUpgrades.js
Labels: ⛓chain

#2116 Docs stronger than ever: small fixes to Rewards contract documentation
  solidity/contracts/BeaconBackportRewards.sol
  solidity/contracts/Rewards.sol
Labels: ⛓chain

#2112 Removed unused internal constant from BeaconBackportRewards
  solidity/contracts/BeaconBackportRewards.sol
Labels: ⛓chain

#2117 Modifications in beacon rewards tests
  solidity/contracts/stubs/KeepRandomBeaconOperatorBeaconRewardsStub.sol
  solidity/test/rewards/TestBeaconBackportRewards.js
  solidity/test/rewards/TestBeaconRewards.js
Labels: ⛓chain

#2127 Logging "relay entry requested event with previous entry.." as warning
  pkg/beacon/beacon.go
Labels: 📟 client

#2133 Failed to check if stale for group public key
  pkg/beacon/beacon.go
  pkg/beacon/relay/registry/groups.go
  pkg/beacon/relay/registry/groups_test.go
Labels: 📟 client

#2124 Phased Escrow: Escrow contract that allows phased release
  solidity/contracts/PhasedEscrow.sol
  solidity/contracts/stubs/TestPhasedEscrowBeneficiaries.sol
  solidity/package.json
  solidity/test/TestPhasedEscrow.js
Labels: ⛓chain

#2136 Improve rewards upgrade handling
  solidity/contracts/Rewards.sol
Labels: ⛓chain

#2101 Header and sec menu
  solidity/dashboard/package.json
  solidity/dashboard/src/App.js
  solidity/dashboard/src/components/Header.jsx
  solidity/dashboard/src/components/Icons.jsx
  solidity/dashboard/src/components/MenuButton.jsx
  solidity/dashboard/src/components/PageWrapper.jsx
  solidity/dashboard/src/components/Routing.jsx
  solidity/dashboard/src/components/SideMenu.jsx
  solidity/dashboard/src/components/resources/Navigation.jsx
  solidity/dashboard/src/css/app.less
  solidity/dashboard/src/css/header.less
  solidity/dashboard/src/css/resources-page.less
  solidity/dashboard/src/css/side-menu.less
  solidity/dashboard/src/css/typography.less
  solidity/dashboard/src/css/vars.less
  solidity/dashboard/src/pages/ApplicationsPageContainer.jsx
  solidity/dashboard/src/pages/KeepRandomBeaconApplicationPage.jsx
  solidity/dashboard/src/pages/OperatorPage.jsx
  solidity/dashboard/src/pages/ResourcesPage.jsx
  solidity/dashboard/src/pages/RewardsPage.jsx
  solidity/dashboard/src/pages/RewardsPageContainer.jsx
  solidity/dashboard/src/pages/TBTCApplicationPage.jsx
  solidity/dashboard/src/pages/TBTCRewardsPage.jsx
  solidity/dashboard/src/pages/TokenGrantsPage.jsx
  solidity/dashboard/src/pages/TokenOverviewPage.jsx
  solidity/dashboard/src/pages/TokensPage.jsx
  solidity/dashboard/src/pages/TokensPageContainer.jsx
  solidity/dashboard/src/static/svg/token-dashboard-logo.svg
Labels: :old_key: token dashboard

#2137 Rewards deallocation tests
  solidity/test/rewards/TestRewardUpgrades.js
Labels: ⛓chain

#2107 Web3 status updates
  solidity/dashboard/src/components/AddressShortcut.jsx
  solidity/dashboard/src/components/CopyToClipboard.jsx
  solidity/dashboard/src/components/Header.jsx
  solidity/dashboard/src/components/Icons.jsx
  solidity/dashboard/src/components/NetworkStatus.jsx
  solidity/dashboard/src/components/Routing.jsx
  solidity/dashboard/src/components/WalletOptions.jsx
  solidity/dashboard/src/components/Web3ContextProvider.jsx
  solidity/dashboard/src/components/Web3Status.jsx
  solidity/dashboard/src/css/address-shortcut.less
  solidity/dashboard/src/css/app.less
  solidity/dashboard/src/css/choose-wallet.less
  solidity/dashboard/src/css/header.less
  solidity/dashboard/src/css/network-status.less
  solidity/dashboard/src/css/vars.less
  solidity/dashboard/src/css/wallet-options.less
  solidity/dashboard/src/css/web3-status.less
  solidity/dashboard/src/static/svg/ledger.svg
  solidity/dashboard/src/static/svg/metamask.svg
  solidity/dashboard/src/static/svg/network-status-indicator.svg
  solidity/dashboard/src/static/svg/trezor.svg
  solidity/dashboard/src/static/svg/wallet.svg
Labels: :old_key: token dashboard

#2125 Fonts updates in the KEEP token dashboard
  solidity/dashboard/src/css/buttons.less
  solidity/dashboard/src/css/fonts/roboto-slab.css
  solidity/dashboard/src/css/fonts/roboto-slab/LICENSE.txt
  solidity/dashboard/src/css/fonts/roboto-slab/RobotoSlab-Black.ttf
  solidity/dashboard/src/css/fonts/roboto-slab/RobotoSlab-Bold.ttf
  solidity/dashboard/src/css/fonts/roboto-slab/RobotoSlab-Light.ttf
  solidity/dashboard/src/css/fonts/roboto-slab/RobotoSlab-Regular.ttf
  solidity/dashboard/src/css/fonts/vitesse.css
  solidity/dashboard/src/css/fonts/vitesse/VitesseSSm-BlackItalic.otf
  solidity/dashboard/src/css/fonts/vitesse/VitesseSSm-BoldItalic.otf
  solidity/dashboard/src/css/fonts/vitesse/VitesseSSm-BookItalic.otf
  solidity/dashboard/src/css/fonts/vitesse/VitesseSSm-Light.otf
  solidity/dashboard/src/css/fonts/vitesse/VitesseSSm-LightItalic.otf
  solidity/dashboard/src/css/fonts/vitesse/VitesseSSm-Medium.otf
  solidity/dashboard/src/css/fonts/vitesse/VitesseSSm-MediumItalic.otf
  solidity/dashboard/src/css/fonts/work-sans.css
  solidity/dashboard/src/css/fonts/work-sans/OFL.txt
  solidity/dashboard/src/css/fonts/work-sans/README.txt
  solidity/dashboard/src/css/fonts/work-sans/WorkSans-Bold.ttf
  solidity/dashboard/src/css/fonts/work-sans/WorkSans-ExtraBold.ttf
  solidity/dashboard/src/css/fonts/work-sans/WorkSans-Medium.ttf
  solidity/dashboard/src/css/fonts/work-sans/WorkSans-Regular.ttf
  solidity/dashboard/src/css/footer.less
  solidity/dashboard/src/css/forms.less
  solidity/dashboard/src/css/typography.less
Labels: :old_key: token dashboard
