Repository keep-network/keep-core, pull requests merged in 2020-11, with the labels that each got.

#2146 Batch processing rewards and terminations
  solidity/contracts/BeaconRewards.sol
  solidity/contracts/Rewards.sol
  solidity/contracts/stubs/RewardsStub.sol
  solidity/test/rewards/TestBeaconRewards.js
  solidity/test/rewards/TestRewards.js
Labels: ⛓chain

#2149 Adding staker rewards escrow beneficiary contracts
  solidity/contracts/PhasedEscrow.sol
  solidity/contracts/stubs/TestPhasedEscrowBeneficiaries.sol
  solidity/test/TestPhasedEscrow.js
Labels: ⛓chain

#2151 Moved ECDSA rewards related beneficiaries contracts
  solidity/contracts/PhasedEscrow.sol
  solidity/contracts/stubs/TestPhasedEscrowBeneficiaries.sol
  solidity/test/TestPhasedEscrow.js
Labels: ⛓chain

#2155 Added PhasedEscrow.withdrawFromEscrow function
  solidity/contracts/PhasedEscrow.sol
  solidity/test/TestPhasedEscrow.js
Labels: ⛓chain

#2156 Backport: Added PhasedEscrow.withdrawFromEscrow function
  solidity/contracts/PhasedEscrow.sol
  solidity/test/TestPhasedEscrow.js
Labels: ⛓chain

#2159 Allow PhasedEscrow to receive tokens via approveAndCall
  solidity/contracts/PhasedEscrow.sol
  solidity/test/TestPhasedEscrow.js
  solidity/test/token_stake/TestTopUps.js
Labels: ⛓chain

#2111 Operator balance monitoring
  cmd/start.go
  configs/config.toml.SAMPLE
  go.mod
  go.sum
  pkg/beacon/relay/registry/groups_test.go
  pkg/chain/chain.go
  pkg/chain/ethereum/balance_monitor.go
  pkg/chain/ethereum/connect.go
  pkg/chain/ethereum/ethereum.go
  pkg/chain/local/local.go
  solidity/scripts/lcl-client-config.js
Labels: 📟 client

#2139 Added Staked beacon mainnet bootstrap nodes
  docs/run-random-beacon.adoc
Labels: :book: documentation

#2148 Update confirmation modal text
  solidity/dashboard/src/components/UndelegateStakeButton.jsx
Labels: :old_key: token dashboard

#2135 Tooltip updates
  solidity/dashboard/src/components/AddressShortcut.jsx
  solidity/dashboard/src/components/Icons.jsx
  solidity/dashboard/src/components/SpeechBubbleTooltip.jsx
  solidity/dashboard/src/components/Tooltip.jsx
  solidity/dashboard/src/components/Undelegations.jsx
  solidity/dashboard/src/css/tooltip.less
Labels: :old_key: token dashboard

#2150 New tokens page
  solidity/dashboard/src/App.js
  solidity/dashboard/src/components/ContractsDataContextProvider.jsx
  solidity/dashboard/src/components/CreateTokenGrantForm.jsx
  solidity/dashboard/src/components/DelegateStakeForm.jsx
  solidity/dashboard/src/components/DelegationOverview.jsx
  solidity/dashboard/src/components/Dropdown.jsx
  solidity/dashboard/src/components/FormInput.jsx
  solidity/dashboard/src/components/Icons.jsx
  solidity/dashboard/src/components/OwnedTokensOverview.jsx
  solidity/dashboard/src/components/ProgressBar.jsx
  solidity/dashboard/src/components/Routing.jsx
  solidity/dashboard/src/components/SelectedGrantDropdown.jsx
  solidity/dashboard/src/components/SideMenu.jsx
  solidity/dashboard/src/components/Tag.jsx
  solidity/dashboard/src/components/TokenGrantOverview.jsx
  solidity/dashboard/src/components/TokensContextSwitcher.jsx
  solidity/dashboard/src/components/TokensOverview.jsx
  solidity/dashboard/src/components/WithOnlyLoggedUserHoc.jsx
  solidity/dashboard/src/constants/colors.js
  solidity/dashboard/src/contexts/TokensPageContext.jsx
  solidity/dashboard/src/css/app.less
  solidity/dashboard/src/css/commons.less
  solidity/dashboard/src/css/delegate-stake-form.less
  solidity/dashboard/src/css/dropdown.less
  solidity/dashboard/src/css/forms.less
  solidity/dashboard/src/css/granted-tokens-page.less
  solidity/dashboard/src/css/progress-bar.less
  solidity/dashboard/src/css/tags.less
  solidity/dashboard/src/css/tokens-context-switcher.less
  solidity/dashboard/src/css/tokens-page.less
  solidity/dashboard/src/css/typography.less
  solidity/dashboard/src/css/vars.less
  solidity/dashboard/src/css/wallet-tokens-page.less
  solidity/dashboard/src/pages/CreateTokenGrantPage.jsx
  solidity/dashboard/src/pages/TokensPage.jsx
  solidity/dashboard/src/pages/TokensPageContainer.jsx
  solidity/dashboard/src/pages/delegation/GrantedTokensPage.jsx
  solidity/dashboard/src/pages/delegation/WalletTokensPage.jsx
  solidity/dashboard/src/pages/delegation/index.js
  solidity/dashboard/src/static/svg/calendar.svg
  solidity/dashboard/src/static/svg/keep-green-outline.svg
  solidity/dashboard/src/static/svg/plus.svg
  solidity/dashboard/src/static/svg/time.svg
Labels: :old_key: token dashboard

#2141 Update app structure
  solidity/dashboard/src/App.js
  solidity/dashboard/src/components/Footer.jsx
  solidity/dashboard/src/css/app.less
Labels: :old_key: token dashboard

#2142 Update external link styles
  solidity/dashboard/src/components/ApplicationBox.jsx
  solidity/dashboard/src/components/Footer.jsx
  solidity/dashboard/src/components/RewardsStatus.jsx
  solidity/dashboard/src/components/ViewInBlockExplorer.jsx
  solidity/dashboard/src/components/ViewTxMsgContent.jsx
  solidity/dashboard/src/css/typography.less
  solidity/dashboard/src/pages/KeepRandomBeaconApplicationPage.jsx
  solidity/dashboard/src/pages/TBTCApplicationPage.jsx
  solidity/dashboard/src/static/svg/link-arrow-grey.svg
  solidity/dashboard/src/static/svg/link-arrow.svg
Labels: :old_key: token dashboard

#2180 Configure Ether value with unit
  .gitignore
  cmd/start.go
  config/config_test.go
  configs/config.toml.SAMPLE
  go.mod
  go.sum
  pkg/chain/ethereum/connect.go
  pkg/chain/gen/abi/BeaconBackportRewards.go
  pkg/chain/gen/abi/BeaconRewards.go
  pkg/chain/gen/abi/KeepRandomBeaconOperator.go
  pkg/chain/gen/abi/PhasedEscrow.go
  pkg/chain/gen/abi/Rewards.go
  pkg/chain/gen/abi/StakeDelegatable.go
  pkg/chain/gen/abi/TokenStaking.go
  pkg/chain/gen/cmd/KeepRandomBeaconOperator.go
  pkg/chain/gen/cmd/KeepRandomBeaconService.go
  pkg/chain/gen/cmd/TokenGrant.go
  pkg/chain/gen/cmd/TokenStaking.go
  pkg/chain/gen/contract/KeepRandomBeaconOperator.go
  pkg/chain/gen/contract/KeepRandomBeaconService.go
  pkg/chain/gen/contract/TokenGrant.go
  pkg/chain/gen/contract/TokenStaking.go
  test/config.toml
Labels: 📟 client
