Repository keep-network/keep-core, pull requests merged in 2020-08, with the labels that each got.

#1945 Top ups in dapp
  solidity/dashboard/src/App.js
  solidity/dashboard/src/components/AddTopUpModal.jsx
  solidity/dashboard/src/components/AmountForm.jsx
  solidity/dashboard/src/components/BondingSection.jsx
  solidity/dashboard/src/components/Button.jsx
  solidity/dashboard/src/components/ChooseWallet.jsx
  solidity/dashboard/src/components/ConfirmationModal.jsx
  solidity/dashboard/src/components/DelegatedTokensTable.jsx
  solidity/dashboard/src/components/DelegationOverview.jsx
  solidity/dashboard/src/components/LedgerModal.jsx
  solidity/dashboard/src/components/Loadable.jsx
  solidity/dashboard/src/components/Modal.jsx
  solidity/dashboard/src/components/ProgressBar.jsx
  solidity/dashboard/src/components/RecoverStakeButton.jsx
  solidity/dashboard/src/components/Tag.jsx
  solidity/dashboard/src/components/TokenGrantOverview.jsx
  solidity/dashboard/src/components/TopUpsDataTable.jsx
  solidity/dashboard/src/components/TrezorModal.jsx
  solidity/dashboard/src/components/UndelegateStakeButton.jsx
  solidity/dashboard/src/components/Web3ContextProvider.jsx
  solidity/dashboard/src/connectors/abstract-connector.js
  solidity/dashboard/src/constants/constants.js
  solidity/dashboard/src/contexts/TokensPageContext.jsx
  solidity/dashboard/src/contracts.js
  solidity/dashboard/src/css/app.less
  solidity/dashboard/src/css/buttons.less
  solidity/dashboard/src/css/indicator.less
  solidity/dashboard/src/css/tags.less
  solidity/dashboard/src/hooks/useCustomOnSubmitFormik.js
  solidity/dashboard/src/hooks/useFetchData.js
  solidity/dashboard/src/hooks/useModal.js
  solidity/dashboard/src/pages/TokenGrantsPage.jsx
  solidity/dashboard/src/pages/TokenOverviewPage.jsx
  solidity/dashboard/src/pages/TokensPage.jsx
  solidity/dashboard/src/pages/TokensPageContainer.jsx
  solidity/dashboard/src/reducers/tokens-page.reducer.js
  solidity/dashboard/src/services/tokens-page.service.js
  solidity/dashboard/src/services/top-ups.service.js
Labels: :old_key: token dashboard, process & client team

#1974 Allow to top-up less than the minimum stake
  solidity/contracts/TokenStaking.sol
  solidity/contracts/libraries/staking/TopUps.sol
  solidity/test/token_stake/TestTopUps.js
Labels: ⛓chain

#1977 Minimum stake schedule starts at the moment of deploying KEEP token
  solidity/contracts/TokenStaking.sol
  solidity/contracts/libraries/operator/Groups.sol
  solidity/contracts/libraries/staking/MinimumStakeSchedule.sol
  solidity/contracts/stubs/MinimumStakeScheduleStub.sol
  solidity/contracts/stubs/TokenStakingStub.sol
  solidity/test/random_beacon_operator/TestSlashing.js
  solidity/test/token_stake/TestMinimumStake.js
  solidity/test/token_stake/TestPunishment.js
  solidity/test/token_stake/TestStakingGrant.js
Labels: process & client team, ⛓chain

#1987 Allow to top-up less than the min stake- dapp
  solidity/dashboard/src/components/AmountForm.jsx
  solidity/dashboard/src/components/DelegatedTokensTable.jsx
  solidity/dashboard/src/components/DelegationOverview.jsx
  solidity/dashboard/src/pages/TokenOverviewPage.jsx
Labels: :old_key: token dashboard

#1981 Allow to copy stake only one time even if it's been recovered
  solidity/contracts/StakingPortBacker.sol
  solidity/test/token_stake/TestStakingPortBacker.js
  solidity/test/token_stake/TestTokenStake.js
Labels: ⛓chain

#1982 Added a note to docs that a top-up can not be cancelled
  solidity/contracts/TokenStaking.sol
Labels: ⛓chain

#1980 Regenerated generated Go contract and command bindings
  pkg/chain/gen/abi/Authorizations.go
  pkg/chain/gen/abi/StakeDelegatable.go
  pkg/chain/gen/abi/StakingPortBacker.go
  pkg/chain/gen/abi/TokenSender.go
  pkg/chain/gen/abi/TokenStaking.go
  pkg/chain/gen/abi/TokenStakingEscrow.go
  pkg/chain/gen/cmd/TokenGrant.go
  pkg/chain/gen/cmd/TokenStaking.go
  pkg/chain/gen/contract/TokenGrant.go
  pkg/chain/gen/contract/TokenStaking.go
  pkg/net/gen/pb/handshake.pb.go
Labels: 📟 client

#1986 Improved documentation around AuthorityVerifier
  solidity/contracts/Authorizations.sol
  solidity/contracts/libraries/staking/Locks.sol
Labels: ⛓chain

#1984 Pass minimum stake schedule start as a parameter to the library
  solidity/contracts/TokenStaking.sol
  solidity/contracts/libraries/staking/MinimumStakeSchedule.sol
Labels: ⛓chain

#1991 Gas price ceiling updates
  solidity/contracts/GasPriceOracle.sol
  solidity/contracts/KeepRandomBeaconOperator.sol
  solidity/contracts/stubs/GasPriceOracleConsumerStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorCallbackStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorDKGResultStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorGroupSelectionStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorInitializationStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorMisbehaviorStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorPricingDKGStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorPricingRewardsWithdrawStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorPricingStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorRewardsStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorServicePricingStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorSlashingStub.sol
  solidity/contracts/stubs/KeepRandomBeaconOperatorStub.sol
  solidity/migrations/2_deploy_contracts.js
  solidity/migrations/3_initialize.js
  solidity/test/TestGasPriceOracle.js
  solidity/test/helpers/initContracts.js
  solidity/test/random_beacon_operator/TestManageServiceContracts.js
  solidity/test/random_beacon_service/TestSelectOperator.js
Labels: ⛓chain

#1990 Replace StakeDelegatable.ownerOperators mapping with an event
  solidity/contracts/StakeDelegatable.sol
  solidity/contracts/TokenStaking.sol
  solidity/test/token_stake/TestTokenStake.js
Labels: ⛓chain

#1959 Expose peers list as JSON via Diagnostics package
  cmd/start.go
  config/config.go
  configs/config.toml.SAMPLE
  go.mod
  go.sum
  pkg/diagnostics/diagnostics.go
  pkg/metrics/metrics.go
Labels: process & client team, 📟 client

#1996 Add GoSec workflow
  .github/workflows/gosec.yml
  cmd/network.go
  config/config.go
  pkg/beacon/beacon.go
  pkg/beacon/beacon_test.go
  pkg/beacon/relay/chain/chain.go
  pkg/beacon/relay/dkg/dkg.go
  pkg/beacon/relay/dkg/result/publish.go
  pkg/beacon/relay/dkg/result/submission.go
  pkg/beacon/relay/entry/entry.go
  pkg/beacon/relay/gjkr/gjkr.go
  pkg/beacon/relay/gjkr/protocol.go
  pkg/beacon/relay/groupselection/groupselection_test.go
  pkg/beacon/relay/groupselection/ticket_submission_test.go
  pkg/beacon/relay/registry/groups_test.go
  pkg/beacon/relay/relay.go
  pkg/beacon/relay/state/machine_test.go
  pkg/chain/ethereum/ethereum.go
  pkg/chain/ethereum/lib.go
  pkg/chain/ethereum/utility.go
  pkg/chain/local/local.go
  pkg/chain/local/local_test.go
  pkg/internal/dkgtest/dkgtest.go
  pkg/internal/entrytest/entrytest.go
  pkg/internal/interception/interception.go
  pkg/internal/interception/interception_test.go
  pkg/net/libp2p/authenticated_connection.go
  pkg/net/libp2p/channel.go
  pkg/net/libp2p/channels_fuzzing_test.go
  pkg/net/libp2p/libp2p_test.go
  pkg/net/local/broadcast_channel.go
  pkg/net/local/broadcast_channel_test.go
  pkg/net/local/identity.go
  pkg/net/net.go
Labels: 📟 client

#1985 Migration to redux- dapp
  solidity/dashboard/package-lock.json
  solidity/dashboard/package.json
  solidity/dashboard/src/App.js
  solidity/dashboard/src/actions/messages.js
  solidity/dashboard/src/actions/web3.js
  solidity/dashboard/src/components/AddETHModal.jsx
  solidity/dashboard/src/components/AuthorizeContracts.jsx
  solidity/dashboard/src/components/Banner.jsx
  solidity/dashboard/src/components/Button.jsx
  solidity/dashboard/src/components/ConfirmationModal.jsx
  solidity/dashboard/src/components/CreateTokenGrantForm.jsx
  solidity/dashboard/src/components/DelegatedTokens.jsx
  solidity/dashboard/src/components/DelegatedTokensTable.jsx
  solidity/dashboard/src/components/DelegationOverview.jsx
  solidity/dashboard/src/components/Message.jsx
  solidity/dashboard/src/components/RecoverStakeButton.jsx
  solidity/dashboard/src/components/Rewards.jsx
  solidity/dashboard/src/components/TokenGrantOverview.jsx
  solidity/dashboard/src/components/TopUpsDataTable.jsx
  solidity/dashboard/src/components/UndelegateStakeButton.jsx
  solidity/dashboard/src/components/ViewTxMsgContent.jsx
  solidity/dashboard/src/components/Web3ContextProvider.jsx
  solidity/dashboard/src/components/WithdrawETHModal.jsx
  solidity/dashboard/src/contexts/TokensPageContext.jsx
  solidity/dashboard/src/contracts.js
  solidity/dashboard/src/hooks/useCustomOnSubmitFormik.js
  solidity/dashboard/src/hooks/useSubscribeToContractEvent.js
  solidity/dashboard/src/pages/CreateTokenGrantPage.jsx
  solidity/dashboard/src/pages/KeepRandomBeaconApplicationPage.jsx
  solidity/dashboard/src/pages/TBTCApplicationPage.jsx
  solidity/dashboard/src/pages/TokenOverviewPage.jsx
  solidity/dashboard/src/pages/TokensPage.jsx
  solidity/dashboard/src/pages/TokensPageContainer.jsx
  solidity/dashboard/src/reducers/index.js
  solidity/dashboard/src/reducers/messages.js
  solidity/dashboard/src/reducers/tokens-page.reducer.js
  solidity/dashboard/src/sagas/index.js
  solidity/dashboard/src/sagas/messages.js
  solidity/dashboard/src/sagas/staking.js
  solidity/dashboard/src/sagas/token-grant.js
  solidity/dashboard/src/sagas/utils.js
  solidity/dashboard/src/sagas/web3.js
  solidity/dashboard/src/services/tbtc-authorization.service.js
  solidity/dashboard/src/services/token-grants.service.js
  solidity/dashboard/src/services/token-staking-escrow.service.js
  solidity/dashboard/src/services/tokens-page.service.js
  solidity/dashboard/src/services/top-ups.service.js
  solidity/dashboard/src/store.js
  solidity/dashboard/src/utils/ethereum.utils.js
Labels: :old_key: token dashboard, process & client team

#2014 Optimize chain config fetching
  pkg/beacon/beacon.go
  pkg/beacon/relay/chain/chain.go
  pkg/beacon/relay/config/config.go
  pkg/beacon/relay/dkg/dkg.go
  pkg/beacon/relay/dkg/result/submission.go
  pkg/beacon/relay/dkg/result/submission_test.go
  pkg/beacon/relay/entry/entry.go
  pkg/beacon/relay/entry/submission.go
  pkg/beacon/relay/groupselection/groupselection.go
  pkg/beacon/relay/groupselection/groupselection_test.go
  pkg/beacon/relay/node.go
  pkg/beacon/relay/relay.go
  pkg/beacon/relay/relay_test.go
  pkg/chain/ethereum/connect.go
  pkg/chain/ethereum/ethereum.go
  pkg/chain/local/local.go
  pkg/internal/dkgtest/dkgtest.go
Labels: process & client team, 📟 client

#2012 Updates for new TokenStaking events in dashboard.
  solidity/dashboard/src/pages/TokensPageContainer.jsx
  solidity/dashboard/src/services/tbtc-authorization.service.js
  solidity/dashboard/src/services/token-grants.service.js
  solidity/dashboard/src/services/token-staking.service.js
  solidity/dashboard/src/services/tokens-page.service.js
Labels: :old_key: token dashboard

#2006 Enable the Ethereum rate limiter
  configs/config.toml.SAMPLE
  pkg/chain/ethereum/connect.go
  solidity/scripts/lcl-client-config.js
Labels: 📟 client

#2019 Require to report timeout if it happened before requesting new entry
  solidity/contracts/KeepRandomBeaconOperator.sol
  solidity/test/random_beacon_operator/TestRelayEntryTimeout.js
  solidity/test/random_beacon_operator/TestSlashing.js
Labels: ⛓chain
