Repository keep-network/keep-core, pull requests merged in 2021-11, with the labels that each got.

#2681 tBTC reward allocation 2021-10-22 -> 2021-10-29
  solidity/dashboard/src/rewards-allocation/rewards.json
Labels: :old_key: token dashboard

#2664 Random Beacon v2 relay entry timeout and slashing
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/Relay.sol
  solidity/random-beacon/contracts/test/RandomBeaconStub.sol
  solidity/random-beacon/contracts/test/RelayStub.sol
  solidity/random-beacon/contracts/test/SortitionPoolStub.sol
  solidity/random-beacon/contracts/test/StakingStub.sol
  solidity/random-beacon/test/RandomBeacon.Callback.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
  solidity/random-beacon/test/fixtures/index.ts
  solidity/random-beacon/test/utils/groups.ts
Labels: ⛓chain

#2679 Clarification renames of DKG result properties, documentation improvements
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/DKG.sol
  solidity/random-beacon/contracts/libraries/Groups.sol
  solidity/random-beacon/contracts/test/GroupsStub.sol
  solidity/random-beacon/test/utils/dkg.ts
Labels: ⛓chain

#2680 Validate `misbehavedMembersIndices` submitted in DKG result
  solidity/random-beacon/contracts/libraries/DKG.sol
Labels: ⛓chain

#2649 Improve modals based on withdrawal status
  solidity-v1/dashboard/src/__tests__/utils/coverage-pools.utils.test.js
  solidity-v1/dashboard/src/components/coverage-pools/IncreaseWithdrawalModal.jsx
  solidity-v1/dashboard/src/components/coverage-pools/PendingWithdrawals.jsx
  solidity-v1/dashboard/src/components/coverage-pools/ReinitiateWithdrawalModal.jsx
  solidity-v1/dashboard/src/components/coverage-pools/WithdrawalInfo.jsx
  solidity-v1/dashboard/src/constants/constants.js
  solidity-v1/dashboard/src/css/increase-withdrawal-modal.less
  solidity-v1/dashboard/src/css/withdraw-modal.less
  solidity-v1/dashboard/src/pages/coverage-pools/CoveragePoolPage.jsx
  solidity-v1/dashboard/src/sagas/coverage-pool.js
  solidity-v1/dashboard/src/utils/coverage-pools.utils.js
Labels: :old_key: token dashboard

#2694 Updated guides with latest ropsten contracts
  docs/run-random-beacon.adoc
Labels: :book: documentation

#2701 Update liquidity cards
  solidity-v1/dashboard/src/components/KeepOnlyPool.jsx
  solidity-v1/dashboard/src/constants/constants.js
  solidity-v1/dashboard/src/pages/liquidity/LiquidityPage.jsx
Labels: :old_key: token dashboard

#2643 `ExchangeRate` component updates
  solidity-v1/dashboard/src/components/coverage-pools/ExchangeRate.jsx
  solidity-v1/dashboard/src/utils/token.utils.js
Labels: :old_key: token dashboard

#2657 Update wallet address in URL after changing account
  solidity-v1/dashboard/src/__tests__/hooks/useWalletAddressFromUrl.test.js
  solidity-v1/dashboard/src/hooks/useAutoWalletAddressInjectIntoUrl.js
Labels: :old_key: token dashboard

#2703 [Backport] Update liquidity pools cards
  solidity/dashboard/src/components/KeepOnlyPool.jsx
  solidity/dashboard/src/constants/constants.js
  solidity/dashboard/src/pages/liquidity/LiquidityPage.jsx
Labels: :old_key: token dashboard

#2690 DKG: rewards for result submission and timeout notification
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/DKG.sol
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
Labels: ⛓chain

#2698 T migration modals (Undelegate + Claim)
  solidity-v1/dashboard/src/components/DelegatedTokens.jsx
  solidity-v1/dashboard/src/components/DelegatedTokensTable.jsx
  solidity-v1/dashboard/src/components/List.jsx
  solidity-v1/dashboard/src/components/RecoverStakeButton.jsx
  solidity-v1/dashboard/src/components/UndelegateStakeButton.jsx
  solidity-v1/dashboard/src/components/Undelegations.jsx
  solidity-v1/dashboard/src/components/modal/ModalRoot.jsx
  solidity-v1/dashboard/src/components/modal/staking/ConfirmUndelegation.jsx
  solidity-v1/dashboard/src/components/modal/staking/claim/ClaimTokens.jsx
  solidity-v1/dashboard/src/components/modal/staking/claim/TokensClaimed.jsx
  solidity-v1/dashboard/src/components/modal/staking/claim/index.js
  solidity-v1/dashboard/src/components/modal/staking/index.js
  solidity-v1/dashboard/src/components/modal/staking/undelegate/UndelegateStake.jsx
  solidity-v1/dashboard/src/components/modal/staking/undelegate/UndelegationInitiated.jsx
  solidity-v1/dashboard/src/components/modal/staking/undelegate/components/InfoList.jsx
  solidity-v1/dashboard/src/components/modal/staking/undelegate/components/index.js
  solidity-v1/dashboard/src/components/modal/staking/undelegate/index.js
  solidity-v1/dashboard/src/constants/constants.js
  solidity-v1/dashboard/src/reducers/staking.js
  solidity-v1/dashboard/src/sagas/subscriptions.js
Labels: :old_key: token dashboard

#2671 Random Beacon v2 banning inactive operators from sortition pool rewards
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/GasStation.sol
  solidity/random-beacon/contracts/libraries/Relay.sol
  solidity/random-beacon/contracts/test/RandomBeaconStub.sol
  solidity/random-beacon/contracts/test/SortitionPoolStub.sol
  solidity/random-beacon/contracts/test/SortitionTreeStub.sol
  solidity/random-beacon/contracts/test/StakingStub.sol
  solidity/random-beacon/hardhat.config.ts
  solidity/random-beacon/package.json
  solidity/random-beacon/test/RandomBeacon.Callback.test.ts
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/RandomBeacon.Pool.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
  solidity/random-beacon/test/fixtures/index.ts
  solidity/random-beacon/test/utils/groups.ts
  solidity/random-beacon/test/utils/sortitionpool.ts
  solidity/random-beacon/yarn.lock
Labels: ⛓chain

#2691 Random Beacon v2 sortition pool locking
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/DKG.sol
  solidity/random-beacon/contracts/test/RandomBeaconStub.sol
  solidity/random-beacon/contracts/test/SortitionPoolStub.sol
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
  solidity/random-beacon/test/fixtures/index.ts
Labels: ⛓chain

#2707 Relay entry improvements
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/RandomBeaconGovernance.sol
  solidity/random-beacon/contracts/test/SortitionPoolStub.sol
  solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
  solidity/random-beacon/test/RandomBeacon.Pool.test.ts
  solidity/random-beacon/test/RandomBeaconGovernance.test.ts
  solidity/random-beacon/test/fixtures/index.ts
Labels: ⛓chain

#2700 DKG: ban misbehaving operators from sortition-pool rewards
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/DKG.sol
  solidity/random-beacon/contracts/test/GroupsStub.sol
  solidity/random-beacon/test/Groups.test.ts
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/utils/dkg.ts
  solidity/random-beacon/test/utils/groups.ts
Labels: ⛓chain

#2668 Threshold Upgrade
  solidity-v1/dashboard/src/components/FormCheckbox.jsx
  solidity-v1/dashboard/src/components/Icons.jsx
  solidity-v1/dashboard/src/components/ProgressBar.jsx
  solidity-v1/dashboard/src/components/RecoverStakeButton.jsx
  solidity-v1/dashboard/src/components/Routing.jsx
  solidity-v1/dashboard/src/components/SideMenu.jsx
  solidity-v1/dashboard/src/components/TokenGrantOverview.jsx
  solidity-v1/dashboard/src/components/TokenOverview.jsx
  solidity-v1/dashboard/src/components/coverage-pools/PendingWithdrawals.jsx
  solidity-v1/dashboard/src/components/modal/ModalRoot.jsx
  solidity-v1/dashboard/src/components/modal/coverage-pools/components/WithdrawalOverview.jsx
  solidity-v1/dashboard/src/components/modal/staking/ViewTransactionSuccessModal.jsx
  solidity-v1/dashboard/src/components/modal/staking/claim/TokensClaimed.jsx
  solidity-v1/dashboard/src/components/modal/threshold/GrantTokensWithdrawn.jsx
  solidity-v1/dashboard/src/components/modal/threshold/WithdrawGrantedTokens.jsx
  solidity-v1/dashboard/src/components/skeletons/TokenAmountSkeleton.jsx
  solidity-v1/dashboard/src/components/threshold/AllocationProgressBar.jsx
  solidity-v1/dashboard/src/components/threshold/UpgradeTokensTile.jsx
  solidity-v1/dashboard/src/constants/constants.js
  solidity-v1/dashboard/src/constants/tooltips.js
  solidity-v1/dashboard/src/css/accordion.less
  solidity-v1/dashboard/src/css/allocation-progress-bar.less
  solidity-v1/dashboard/src/css/app.less
  solidity-v1/dashboard/src/css/threshold-page.less
  solidity-v1/dashboard/src/css/typography.less
  solidity-v1/dashboard/src/css/upgrade-tokens-tile.less
  solidity-v1/dashboard/src/css/withdraw-granted-tokens.less
  solidity-v1/dashboard/src/hooks/useGrantedBalanceInfo.js
  solidity-v1/dashboard/src/hooks/useKeepBalanceInfo.js
  solidity-v1/dashboard/src/lib/keep/contracts/index.js
  solidity-v1/dashboard/src/pages/OverviewPage.jsx
  solidity-v1/dashboard/src/pages/coverage-pools/index.js
  solidity-v1/dashboard/src/pages/delegation/WalletTokensPage.jsx
  solidity-v1/dashboard/src/pages/rewards/TBTCRewardsPage.jsx
  solidity-v1/dashboard/src/pages/tbtc-migration/index.js
  solidity-v1/dashboard/src/pages/threshold/HowItWorksPage.jsx
  solidity-v1/dashboard/src/pages/threshold/ThresholdUpgradePage.jsx
  solidity-v1/dashboard/src/pages/threshold/index.js
  solidity-v1/dashboard/src/reducers/token-grant.js
  solidity-v1/dashboard/src/reducers/tokens-page.reducer.js
  solidity-v1/dashboard/src/sagas/subscriptions.js
  solidity-v1/dashboard/src/static/svg/chevron-down.svg
  solidity-v1/dashboard/src/static/svg/chevron-up.svg
  solidity-v1/dashboard/src/static/svg/keep-t-upgrade-logo.svg
  solidity-v1/dashboard/src/static/svg/star.svg
  solidity-v1/dashboard/src/static/svg/t-token-symbol.svg
Labels: :old_key: token dashboard

#2699 Use real sortition pools in DKG tests
  solidity/random-beacon/contracts/test/SortitionPoolStub.sol
  solidity/random-beacon/contracts/test/SortitionTreeStub.sol
  solidity/random-beacon/test/RandomBeacon.Callback.test.ts
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
  solidity/random-beacon/test/RandomBeaconGovernance.test.ts
  solidity/random-beacon/test/fixtures/index.ts
  solidity/random-beacon/test/utils/dkg.ts
  solidity/random-beacon/test/utils/groups.ts
  solidity/random-beacon/test/utils/operators.ts
Labels: ⛓chain

#2714 Eliminated ISortitionPool from RandomBeacon contract
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/DKG.sol
  solidity/random-beacon/contracts/libraries/Relay.sol
  solidity/random-beacon/contracts/test/RandomBeaconStub.sol
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/RandomBeacon.Pool.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
  solidity/random-beacon/test/utils/operators.ts
Labels: ⛓chain

#2708 Governable minimum authorization amount
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/RandomBeaconGovernance.sol
  solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
  solidity/random-beacon/test/RandomBeaconGovernance.test.ts
Labels: ⛓chain

#2709 Allow anyone to approve the DKG result if the submitter is late
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/DKG.sol
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/utils/groups.ts
Labels: ⛓chain

#2719 Added governable authorization decrease delay parameter
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/RandomBeaconGovernance.sol
  solidity/random-beacon/contracts/libraries/Authorization.sol
  solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
  solidity/random-beacon/test/RandomBeaconGovernance.test.ts
Labels: ⛓chain

#2720 Expect 33 signatures on the DKG result
  solidity/random-beacon/contracts/libraries/DKG.sol
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/utils/dkg.ts
Labels: ⛓chain

#2695 Random Beacon v2 DKG challenge verification and slashing
  solidity/random-beacon/.solhintignore
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/RandomBeaconGovernance.sol
  solidity/random-beacon/contracts/libraries/DKG.sol
  solidity/random-beacon/contracts/test/RandomBeaconStub.sol
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
  solidity/random-beacon/test/RandomBeaconGovernance.test.ts
  solidity/random-beacon/test/utils/dkg.ts
  solidity/random-beacon/test/utils/groups.ts
Labels: ⛓chain

#2723 Remove fields from relay library
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/Relay.sol
Labels: ⛓chain

#2686 Adding group status
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/RandomBeaconGovernance.sol
  solidity/random-beacon/contracts/libraries/Groups.sol
  solidity/random-beacon/contracts/libraries/Relay.sol
  solidity/random-beacon/contracts/test/GroupsStub.sol
  solidity/random-beacon/contracts/test/RandomBeaconStub.sol
  solidity/random-beacon/test/Groups.Expiration.test.ts
  solidity/random-beacon/test/Groups.Termination.test.ts
  solidity/random-beacon/test/Groups.test.ts
  solidity/random-beacon/test/RandomBeacon.Callback.test.ts
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
Labels: ⛓chain

#2733 Clarified there can only one candidate group - description and tests
  solidity-v1/contracts/cryptography/BLS.sol
  solidity/random-beacon/contracts/libraries/BLS.sol
  solidity/random-beacon/contracts/libraries/Groups.sol
  solidity/random-beacon/test/Groups.test.ts
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
Labels: ⛓chain

#2682 [Backport] tBTC reward allocation 2021-10-22 -> 2021-10-29; 2021-10-29 -> 2021-11-05
  solidity-v1/dashboard/src/rewards-allocation/rewards.json
Labels: :old_key: token dashboard

#2693 tBTC reward allocation 2021-10-29 -> 2021-11-05
  solidity/dashboard/src/rewards-allocation/rewards.json
Labels: :old_key: token dashboard

#2710 tBTC reward allocation 2021-11-05 -> 2021-11-12
  solidity/dashboard/src/rewards-allocation/rewards.json
Labels: :old_key: token dashboard

#2711 tBTC reward allocation 2021-11-12 -> 2021-11-19
  solidity/dashboard/src/rewards-allocation/rewards.json
Labels: :old_key: token dashboard

#2712 [Backport] tBTC reward allocation 2021-11-05 -> 2021-11-12
  solidity-v1/dashboard/src/rewards-allocation/rewards.json
Labels: :old_key: token dashboard

#2713 [Backport] tBTC reward allocation 2021-11-12 -> 2021-11-19
  solidity-v1/dashboard/src/rewards-allocation/rewards.json
Labels: :old_key: token dashboard

#2737 Updated `sortition-pools` dependency to the most recent one
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/test/StakingStub.sol
  solidity/random-beacon/package.json
  solidity/random-beacon/test/RandomBeacon.Pool.test.ts
  solidity/random-beacon/test/fixtures/index.ts
  solidity/random-beacon/yarn.lock
Labels: ⛓chain

#2738 tBTC reward allocation 2021-11-19 -> 2021-11-26
  solidity/dashboard/src/rewards-allocation/rewards.json
Labels: :old_key: token dashboard

#2729 Remove relay entry eligibility checks
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/Relay.sol
  solidity/random-beacon/contracts/libraries/Submission.sol
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
Labels: ⛓chain

#2735 Separate rewards pools for DKG and heartbeats
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
Labels: ⛓chain

#2734 Moved DKG result signature validation to challengeDkgResult
  solidity/random-beacon/.solhintignore
  solidity/random-beacon/contracts/DKGValidator.sol
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/DKG.sol
  solidity/random-beacon/contracts/test/RandomBeaconStub.sol
  solidity/random-beacon/test/DKGValidator.test.ts
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/fixtures/index.ts
  solidity/random-beacon/test/utils/dkg.ts
  solidity/random-beacon/test/utils/groups.ts
Labels: ⛓chain

#2705 Terminating groups on relay entry timeout and reporting unauthorised signing
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/RandomBeaconGovernance.sol
  solidity/random-beacon/contracts/test/RandomBeaconStub.sol
  solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
  solidity/random-beacon/test/RandomBeaconGovernance.test.ts
Labels: ⛓chain
