Repository keep-network/keep-core, pull requests merged in 2022-08, with the labels that each got.

#3116 Use immutable fields for SortitionPool
  solidity/ecdsa/contracts/EcdsaDkgValidator.sol
  solidity/random-beacon/contracts/BeaconDkgValidator.sol
Labels: ⛓chain

#3061 Görli contracts deployment
  .github/workflows/contracts-random-beacon.yml
  solidity/ecdsa/deploy/00_resolve_reimbursement_pool.ts
  solidity/ecdsa/deploy/00_resolve_token_staking.ts
  solidity/ecdsa/deploy/01_deploy_ecdsa_sortition_pool.ts
  solidity/ecdsa/deploy/02_deploy_dkg_validator.ts
  solidity/ecdsa/deploy/03_deploy_wallet_registry.ts
  solidity/ecdsa/deploy/04_approve_wallet_registry.ts
  solidity/ecdsa/deploy/05_authorize_wallet_registry.ts
  solidity/ecdsa/deploy/06_deploy_wallet_registry_governance.ts
  solidity/ecdsa/deploy/07_transfer_governance.ts
  solidity/ecdsa/deploy/08_transfer_proxy_admin_ownership.ts
  solidity/ecdsa/deploy/09_deploy_proxy_admin_with_deputy.ts
  solidity/ecdsa/deploy/10_authorize_in_random_beacon.ts
  solidity/ecdsa/hardhat.config.ts
  solidity/ecdsa/package.json
  solidity/ecdsa/tasks/initialize-wallet-owner.ts
  solidity/random-beacon/.gitignore
  solidity/random-beacon/deploy/01_deploy_reimbursement_pool.ts
  solidity/random-beacon/deploy/02_deploy_beacon_sortition_pool.ts
  solidity/random-beacon/deploy/03_deploy_beacon_dkg_validator.ts
  solidity/random-beacon/deploy/04_deploy_random_beacon.ts
  solidity/random-beacon/deploy/05_approve_random_beacon_in_token_staking.ts
  solidity/random-beacon/deploy/06_authorize_random_beacon_in_reimbursement_pool.ts
  solidity/random-beacon/deploy/07_deploy_random_beacon_governance.ts
  solidity/random-beacon/deploy/08_transfer_governance.ts
  solidity/random-beacon/hardhat.config.ts
  solidity/random-beacon/package.json
  solidity/random-beacon/test/ReimbursementPool.test.ts
  solidity/random-beacon/yarn.lock
Labels: ⛓chain

#3096 Installation tasks for random beacon (refactor) and ecdsa/tbtc
  scripts/initialize.sh
  scripts/install.sh
  solidity/ecdsa/hardhat.config.ts
  solidity/random-beacon/hardhat.config.ts
Labels: 📟 client

#3112 ECDSA DKG test loop: Actual protocol logic
  go.mod
  go.sum
  pkg/chain/ethereum/tbtc.go
  pkg/ecdsa/dkg/dkg.go
  pkg/ecdsa/dkg/gen/gen.go
  pkg/ecdsa/dkg/gen/pb/message.pb.go
  pkg/ecdsa/dkg/gen/pb/message.proto
  pkg/ecdsa/dkg/marshaling.go
  pkg/ecdsa/dkg/marshaling_test.go
  pkg/ecdsa/dkg/member.go
  pkg/ecdsa/dkg/member_test.go
  pkg/ecdsa/dkg/message.go
  pkg/ecdsa/dkg/message_test.go
  pkg/ecdsa/dkg/params_pool.go
  pkg/ecdsa/dkg/params_pool_test.go
  pkg/ecdsa/dkg/protocol.go
  pkg/ecdsa/dkg/protocol_test.go
  pkg/ecdsa/dkg/result.go
  pkg/ecdsa/dkg/states.go
  pkg/protocol/group/group.go
  pkg/tbtc/node.go
Labels: 📟 client

#3115 #3012 Add LoadBalancer with static IP
  infrastructure/kube/keep-test/geth-node/eth-goerli-node.yaml
Labels: :cloud: infrastructure, 📟 client

#3119 One More Once: Keygen Retry Algorithm
  pkg/ecdsa/retry/retry.go
  pkg/ecdsa/retry/retry_test.go
Labels: 📟 client

#3137 Added extra gas requirement for Beacon DKG result challenge
  solidity/ecdsa/contracts/WalletRegistry.sol
  solidity/ecdsa/contracts/libraries/EcdsaDkg.sol
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/RandomBeaconGovernance.sol
  solidity/random-beacon/contracts/libraries/BeaconDkg.sol
  solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
  solidity/random-beacon/test/RandomBeacon.Relay.test.ts
  solidity/random-beacon/test/RandomBeaconGovernance.test.ts
  solidity/random-beacon/test/fixtures/index.ts
  solidity/random-beacon/test/utils/dkg.ts
Labels: ⛓chain

#3140 #3012 Expand PV capacity
  infrastructure/kube/keep-test/geth-node/eth-goerli-node.yaml
Labels: :cloud: infrastructure

#3131 Remove openzeppelin manifest for fresh installation
  scripts/install.sh
Labels: 📟 client

#2996 Improve description of steps for generating PDF, PNG files
  docs/diagrams/system-flow.tikz
Labels: :book: documentation

#2997 Rename `docs.yml` to `docs-v1.yml`
  .github/workflows/docs-v1.yml
Labels: :book: documentation

#3130 Storage layer for `pkg/tbtc`
  cmd/start.go
  pkg/ecdsa/dkg/result.go
  pkg/internal/tecdsatest/tecdsatest.go
  pkg/internal/tecdsatest/testdata/private_key_share_data_0.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_1.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_2.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_3.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_4.json
  pkg/tbtc/gen/gen.go
  pkg/tbtc/gen/pb/wallet.pb.go
  pkg/tbtc/gen/pb/wallet.proto
  pkg/tbtc/marshaling.go
  pkg/tbtc/marshaling_test.go
  pkg/tbtc/node.go
  pkg/tbtc/registry.go
  pkg/tbtc/registry_test.go
  pkg/tbtc/wallet.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/gen/gen.go
  pkg/tecdsa/dkg/gen/pb/message.pb.go
  pkg/tecdsa/dkg/gen/pb/message.proto
  pkg/tecdsa/dkg/marshaling.go
  pkg/tecdsa/dkg/marshaling_test.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/member_test.go
  pkg/tecdsa/dkg/message.go
  pkg/tecdsa/dkg/params_pool.go
  pkg/tecdsa/dkg/params_pool_test.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/dkg/result.go
  pkg/tecdsa/dkg/states.go
  pkg/tecdsa/gen/gen.go
  pkg/tecdsa/gen/pb/key.pb.go
  pkg/tecdsa/gen/pb/key.proto
  pkg/tecdsa/key.go
  pkg/tecdsa/marshaling.go
  pkg/tecdsa/marshaling_test.go
  pkg/tecdsa/retry/retry.go
  pkg/tecdsa/retry/retry_test.go
Labels: 📟 client

#3152 Updating installation scripts docs
  docs/development/README.adoc
  scripts/initialize.sh
Labels: 📟 client

#3160 Allow configuring tECDSA parameters for the client
  cmd/flags.go
  cmd/flags_test.go
  cmd/start.go
  config/config.go
  configs/config.toml.SAMPLE
  docs/development/cmd-help
  pkg/tbtc/node.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/params_pool.go
Labels: 📟 client

#3162 Abstraction to manage computationally-heavy operation
  pkg/internal/testutils/testutils.go
  pkg/miner/miner.go
  pkg/miner/miner_test.go
Labels: 📟 client

#3168 Marshal pre-parameters
  pkg/beacon/dkg/result/gen/gen.go
  pkg/beacon/entry/gen/gen.go
  pkg/beacon/gjkr/gen/gen.go
  pkg/beacon/registry/gen/gen.go
  pkg/net/gen/gen.go
  pkg/tecdsa/dkg/gen/gen.go
  pkg/tecdsa/gen/gen.go
  pkg/tecdsa/gen/pb/key.pb.go
  pkg/tecdsa/gen/pb/preparams.pb.go
  pkg/tecdsa/gen/pb/preparams.proto
  pkg/tecdsa/marshaling.go
  pkg/tecdsa/marshaling_test.go
  pkg/tecdsa/preparams.go
Labels: 📟 client

#3171 Added a delay between pre-parameters generation
  cmd/flags.go
  cmd/flags_test.go
  configs/config.toml.SAMPLE
  docs/development/cmd-help
  pkg/tbtc/node.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/params_pool.go
  pkg/tecdsa/dkg/params_pool_test.go
Labels: 📟 client

#3172 ParameterPool abstraction
  .github/workflows/client.yml
  pkg/miner/pool.go
  pkg/miner/pool_test.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/gen/pb/preparams.pb.go
  pkg/tecdsa/dkg/gen/pb/preparams.proto
  pkg/tecdsa/dkg/marshaling.go
  pkg/tecdsa/dkg/marshaling_test.go
  pkg/tecdsa/dkg/params_pool.go
  pkg/tecdsa/dkg/params_pool_test.go
  pkg/tecdsa/dkg/preparams.go
  pkg/tecdsa/marshaling.go
  pkg/tecdsa/marshaling_test.go
  pkg/tecdsa/preparams.go
Labels: 📟 client

#3174 Block miner computations until everyone agrees to resume
  pkg/miner/miner.go
  pkg/miner/miner_test.go
  pkg/miner/pool_test.go
Labels: 📟 client

#3177 Updated TSS lib dependency
  go.mod
  go.sum
  pkg/internal/tecdsatest/tecdsatest.go
  pkg/tecdsa/dkg/marshaling.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/member_test.go
  pkg/tecdsa/dkg/preparams.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/key.go
  pkg/tecdsa/marshaling.go
  pkg/tecdsa/marshaling_test.go
Labels: 📟 client

#3180 Cancel the context of worker function when miner is stopped
  pkg/miner/miner.go
  pkg/miner/miner_test.go
  pkg/miner/pool.go
  pkg/miner/pool_test.go
  pkg/tecdsa/dkg/preparams.go
Labels: 📟 client

#3148 Start a client
  scripts/install.sh
  scripts/start.sh
Labels: 📟 client

#3179 Ensure existence of the application storage directory
  cmd/start.go
Labels: 📟 client

#3183 Pre-param generation: cleanup and wiring this together
  cmd/flags_test.go
  cmd/start.go
  pkg/beacon/beacon.go
  pkg/beacon/node.go
  pkg/generator/generator.go
  pkg/generator/latch.go
  pkg/generator/latch_test.go
  pkg/generator/pool.go
  pkg/generator/pool_test.go
  pkg/generator/scheduler.go
  pkg/generator/scheduler_test.go
  pkg/miner/miner.go
  pkg/miner/miner_test.go
  pkg/tbtc/node.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/preparams.go
Labels: 📟 client

#3163 Read keyfile and select the address
  scripts/initialize.sh
Labels: 📟 client

#3190 Use forked sorition pools in testnet deployment
  .github/workflows/contracts-ecdsa.yml
  .github/workflows/contracts-random-beacon.yml
Labels: :cloud: infrastructure

#3192 Update preparation of the artifacts for `solidity-contracts` in `start_dashboard.sh` script
  scripts/start_dashboard.sh
Labels: :cloud: infrastructure, :old_key: token dashboard

#3191 Fix blocked undelegate button
  .git-blame-ignore-revs
  solidity-v1/dashboard/src/lib/keep/keep-to-t-staking/index.js
  solidity-v1/dashboard/src/services/tokens-page.service.js
Labels: :old_key: token dashboard

#3173 Handle long-running computations in tECDSA DKG states
  pkg/beacon/dkg/result/states.go
  pkg/beacon/gjkr/states.go
  pkg/protocol/state/machine.go
  pkg/protocol/state/machine_test.go
  pkg/protocol/state/state.go
  pkg/tecdsa/dkg/states.go
Labels: 📟 client

#3197 Do not allow for nil elements in parameter pool
  pkg/generator/pool.go
  pkg/generator/pool_test.go
Labels: 📟 client

#3196 Improvements for the beacon DKG result submitter
  pkg/beacon/dkg/result/submission.go
Labels: 📟 client

#3181 Use cobra for ethereum command
  cmd/cmd.go
  cmd/ethereum.go
  cmd/flag/flag.go
  cmd/flag/flag_test.go
  cmd/flag/flag_wei.go
  cmd/flags.go
  cmd/flags_test.go
  cmd/start.go
  config/category.go
  config/config.go
  config/config_test.go
  go.mod
  go.sum
  main.go
  pkg/beacon/registry/storage.go
  pkg/chain/ethereum/beacon/gen/abi/RandomBeacon.go
  pkg/chain/ethereum/beacon/gen/cmd/BeaconSortitionPool.go
  pkg/chain/ethereum/beacon/gen/cmd/RandomBeacon.go
  pkg/chain/ethereum/beacon/gen/cmd/cmd.go
  pkg/chain/ethereum/beacon/gen/contract/RandomBeacon.go
  pkg/chain/ethereum/ecdsa/gen/abi/WalletRegistry.go
  pkg/chain/ethereum/ecdsa/gen/cmd/EcdsaSortitionPool.go
  pkg/chain/ethereum/ecdsa/gen/cmd/WalletRegistry.go
  pkg/chain/ethereum/ecdsa/gen/cmd/cmd.go
  pkg/chain/ethereum/ecdsa/gen/contract/WalletRegistry.go
  pkg/chain/ethereum/tbtc/gen/cmd/Bridge.go
  pkg/chain/ethereum/tbtc/gen/cmd/cmd.go
  pkg/chain/ethereum/threshold/gen/cmd/TokenStaking.go
  pkg/chain/ethereum/threshold/gen/cmd/cmd.go
  pkg/diagnostics/diagnostics.go
  pkg/metrics/metrics.go
Labels: 📟 client

#3199 Ensure existence of application storage directory
  cmd/start.go
Labels: 📟 client

#3193 [Backport] Remove specific stakes from t auth data
  solidity-v1/dashboard/src/components/threshold/AuthorizeThresholdContracts.jsx
  solidity-v1/dashboard/src/reducers/threshold-authorization.js
  solidity-v1/dashboard/src/services/threshold-authorization.service.js
Labels: :old_key: token dashboard

#3194 [Backport] Fix blocked undelegate button when unstaking all tokens from t dahboard
  .git-blame-ignore-revs
  solidity-v1/dashboard/src/lib/keep/keep-to-t-staking/index.js
  solidity-v1/dashboard/src/services/tokens-page.service.js
Labels: :old_key: token dashboard

#3169 ECDSA DKG test loop: Retries
  pkg/beacon/dkg/dkg.go
  pkg/beacon/gjkr/protocol.go
  pkg/chain/address.go
  pkg/chain/ethereum/beacon.go
  pkg/chain/ethereum/tbtc.go
  pkg/net/gen/gen.go
  pkg/net/security/handshake/connection_handshake.go
  pkg/protocol/state/machine.go
  pkg/tbtc/chain.go
  pkg/tbtc/node.go
  pkg/tbtc/node_test.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/errors.go
  pkg/tecdsa/dkg/gen/pb/message.pb.go
  pkg/tecdsa/dkg/gen/pb/message.proto
  pkg/tecdsa/dkg/marshaling.go
  pkg/tecdsa/dkg/marshaling_test.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/message.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/dkg/states.go
Labels: 📟 client

#3206 Do not wrap nil inside PreParams in generateFn
  pkg/tecdsa/dkg/preparams.go
Labels: 📟 client

#3120 ECDSA DKG result submission
  pkg/chain/ethereum/tbtc.go
  pkg/tbtc/chain.go
  pkg/tbtc/node.go
  pkg/tbtc/node_test.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/gen/pb/message.pb.go
  pkg/tecdsa/dkg/gen/pb/message.proto
  pkg/tecdsa/dkg/gen/pb/preparams.pb.go
  pkg/tecdsa/dkg/marshaling.go
  pkg/tecdsa/dkg/marshaling_test.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/message.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/dkg/result.go
  pkg/tecdsa/dkg/states.go
  pkg/tecdsa/gen/pb/key.pb.go
Labels: 📟 client

#3200 Embed predefined bootstrap peers list into the client
  cmd/flags.go
  cmd/flags_test.go
  cmd/start.go
  config/_peers/goerli
  config/_peers/mainnet
  config/config.go
  config/peers.go
  config/peers_test.go
  docs/development/cmd-help
  go.mod
  go.sum
  scripts/start.sh
Labels: 📟 client

#3208 Revert accidental formatting changes
  pkg/beacon/dkg/dkg.go
  pkg/beacon/gjkr/protocol.go
  pkg/chain/ethereum/beacon.go
  pkg/chain/ethereum/tbtc.go
  pkg/net/gen/gen.go
  pkg/net/security/handshake/connection_handshake.go
Labels: 📟 client

#3202 tECDSA DKG: Deduplicate received messages by senders
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/dkg/states.go
Labels: 📟 client

#3213 Add workflow building and publishing docs from `docs` folder
  .github/workflows/docs-v1.yml
  .github/workflows/docs.yml
Labels: :book: documentation

#3201 tECDSA signing: Properly map DKG result to a wallet signing group
  pkg/tbtc/node.go
  pkg/tbtc/node_test.go
  pkg/tbtc/wallet.go
Labels: 📟 client

#3212 Provide a cancel signal for the parameter pool getter
  pkg/generator/pool.go
  pkg/generator/pool_test.go
  pkg/tecdsa/dkg/dkg.go
Labels: 📟 client

#3216 Add Private Testnet bundles generator
  infrastructure/eth-networks/private-testnet/.gitignore
  infrastructure/eth-networks/private-testnet/README.adoc
  infrastructure/eth-networks/private-testnet/bundles/bundle-guide.adoc
  infrastructure/eth-networks/private-testnet/scripts/init-provider.sh
  infrastructure/eth-networks/private-testnet/scripts/new-bundle.sh
Labels: :cloud: infrastructure

#3215 Updates to the CLI commands and flags
  cmd/cmd.go
  cmd/ethereum.go
  cmd/flags.go
  cmd/flags_test.go
  cmd/network.go
  cmd/start.go
  config/config.go
  go.mod
  go.sum
  main.go
  pkg/chain/ethereum/beacon/gen/cmd/BeaconSortitionPool.go
  pkg/chain/ethereum/beacon/gen/cmd/RandomBeacon.go
  pkg/chain/ethereum/beacon/gen/cmd/cmd.go
  pkg/chain/ethereum/cmd.go
  pkg/chain/ethereum/ecdsa/gen/cmd/EcdsaSortitionPool.go
  pkg/chain/ethereum/ecdsa/gen/cmd/WalletRegistry.go
  pkg/chain/ethereum/ecdsa/gen/cmd/cmd.go
  pkg/chain/ethereum/tbtc/gen/cmd/Bridge.go
  pkg/chain/ethereum/tbtc/gen/cmd/cmd.go
  pkg/chain/ethereum/threshold/gen/cmd/TokenStaking.go
  pkg/chain/ethereum/threshold/gen/cmd/cmd.go
Labels: 📟 client

#3211 Iniitial documentation for V2 client
  .github/workflows/docs.yml
  Makefile
  docs/dev-ops.adoc
  docs/development/README.adoc
  docs/development/local-t-network.adoc
  docs/index.adoc
  docs/registration.adoc
  docs/resources/client-start-help
  docs/resources/client-start-mainnet-sample
  docs/resources/docker-start-mainnet-sample
  docs/resources/docker-start-testnet-sample
  docs/rfc/rfc-19-random-beacon-v2.adoc
  docs/run-keep-node.adoc
  infrastructure/eth-networks/private-testnet/.gitignore
  infrastructure/eth-networks/private-testnet/README.adoc
  infrastructure/eth-networks/private-testnet/bundles/bundle-guide.adoc
  infrastructure/eth-networks/private-testnet/scripts/init-provider.sh
  infrastructure/eth-networks/private-testnet/scripts/new-bundle.sh
Labels: :book: documentation

#3209 tECDSA signing: Cleanup `node.go`
  pkg/tbtc/dkg.go
  pkg/tbtc/dkg_test.go
  pkg/tbtc/node.go
Labels: 📟 client

#3220 Build client with passing the version and revision
  Makefile
Labels: 📟 client

#3221 Make Docker build use `make build` command
  .github/workflows/client.yml
  Dockerfile
Labels: 📟 client
