Repository keep-network/keep-core, pull requests merged in 2022-09, with the labels that each got.

#3214 Add comment to PR-s modifying docs that links to the published preview
  .github/workflows/docs.yml
Labels: :book: documentation

#3236 Update Run Keep Node documentation
  docs/resources/client-start-help
  docs/run-keep-node.adoc
Labels: :book: documentation

#3232 Add Boar Network bootstrap node to Goerli peers
  config/_peers/goerli
  config/peers_test.go
Labels: 📟 client

#3233 Add missing gen directories to the Dockerfile
  Dockerfile
Labels: :cloud: infrastructure, 📟 client

#3230 Print Operator address in the node header
  cmd/helpers.go
  cmd/start.go
  docs/run-keep-node.adoc
  pkg/chain/ethereum/signer.go
  pkg/chain/local_v1/signer.go
  pkg/chain/signing.go
Labels: 📟 client

#3231 Fix random beacon registration hardhat task
  solidity/random-beacon/tasks/initialize.ts
Labels: 📟 client

#3128 k8s: keep-test configuration for keep-client nodes
  infrastructure/kube/keep-test/eth-account-info-configmap.yaml
  infrastructure/kube/keep-test/eth-network-internal-configmap.yaml
  infrastructure/kube/keep-test/eth-network-ropsten-configmap.yaml
  infrastructure/kube/keep-test/keep-client-0-service.yaml
  infrastructure/kube/keep-test/keep-client-0-statefulset.yaml
  infrastructure/kube/keep-test/keep-client-1-service.yaml
  infrastructure/kube/keep-test/keep-client-1-statefulset.yaml
  infrastructure/kube/keep-test/keep-client-2-service.yaml
  infrastructure/kube/keep-test/keep-client-2-statefulset.yaml
  infrastructure/kube/keep-test/keep-client-3-service.yaml
  infrastructure/kube/keep-test/keep-client-3-statefulset.yaml
  infrastructure/kube/keep-test/keep-client-4-service.yaml
  infrastructure/kube/keep-test/keep-client-4-statefulset.yaml
  infrastructure/kube/keep-test/keep-client/README.md
  infrastructure/kube/keep-test/keep-client/gen.sh
  infrastructure/kube/keep-test/keep-client/gen/data.yaml
  infrastructure/kube/keep-test/keep-client/gen/schema.yaml
  infrastructure/kube/keep-test/keep-client/gen/template.yaml
  infrastructure/kube/keep-test/keep-client/keep-client-config.yaml
  infrastructure/kube/keep-test/keep-client/keep-clients.yaml
Labels: :cloud: infrastructure

#3219 tECDSA signing: Setup of the test loop and signing executor
  pkg/chain/ethereum/tbtc.go
  pkg/tbtc/chain.go
  pkg/tbtc/marshaling.go
  pkg/tbtc/node.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/signing/result.go
  pkg/tecdsa/signing/signing.go
Labels: 📟 client

#3238 Add --detach to sample docker run commands
  docs/resources/docker-start-mainnet-sample
  docs/resources/docker-start-testnet-sample
Labels: :book: documentation

#3226 tECDSA signing: Ephemeral key exchange and symmetric keys generation
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/signing/errors.go
  pkg/tecdsa/signing/gen/gen.go
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/member_test.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3228 tECDSA signing: TSS round 1
  pkg/beacon/gjkr/gen/pb/message.pb.go
  pkg/beacon/gjkr/gen/pb/message.proto
  pkg/chain/ethereum/tbtc.go
  pkg/internal/tecdsatest/testdata/private_key_share_data_0.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_1.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_2.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_3.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_4.json
  pkg/tbtc/node.go
  pkg/tecdsa/common/common.go
  pkg/tecdsa/common/common_test.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/member_test.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/key.go
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/member_test.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3217 Unit tests for DKG result signatures verification phase
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/dkg/states.go
Labels: 📟 client

#3239 tECDSA signing: TSS round 2
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3244 Update port in the Private Testnet bundle's metrics command
  infrastructure/eth-networks/private-testnet/bundles/bundle-guide.adoc
Labels: :book: documentation, :cloud: infrastructure

#3241 tECDSA signing: TSS round 3
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/states.go
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3242 tECDSA signing: TSS round 4
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3243 tECDSA signing: TSS round 5
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3246 tECDSA signing: TSS round 6
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3248 tECDSA signing: TSS round 7
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3249 tECDSA signing: TSS round 8
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3250 tECDSA signing: TSS round 9
  pkg/internal/tecdsatest/tecdsatest.go
  pkg/internal/tecdsatest/testdata/private_key_share_data_0.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_1.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_2.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_3.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_4.json
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3261 Updated .gitignore
  .gitignore
Labels: 📟 client

#3254 tECDSA signing: Consistent party key between TSS runs
  pkg/internal/tecdsatest/testdata/private_key_share_data_0.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_1.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_2.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_3.json
  pkg/internal/tecdsatest/testdata/private_key_share_data_4.json
  pkg/tbtc/node.go
  pkg/tecdsa/common/common.go
  pkg/tecdsa/common/common_test.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/member_test.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/member_test.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
Labels: 📟 client

#3259 tECDSA signing: Phase duration tweaks
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3252 Made client-format check fail on wrongly formatted go code
  .github/workflows/client.yml
  pkg/tbtc/dkg.go
  pkg/tecdsa/common/common_test.go
  pkg/tecdsa/dkg/member_test.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member_test.go
  pkg/tecdsa/signing/message.go
Labels: 📟 client

#3262 tECDSA signing: Consistent party key between TSS runs [followup]
  pkg/tecdsa/common/common.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/member_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/member_test.go
Labels: 📟 client

#3234 Extend diagnostics to show the client version
  .gitignore
  Makefile
  build/build.go
  cmd/start.go
  main.go
  pkg/diagnostics/diagnostics.go
Labels: 📟 client

#3170 Updating docs for installation scripts
  docs/development/README.adoc
Labels: 📟 client

#3263 Follow-up for protobuf upgrade
  go.mod
  scripts/ubuntu-setup.sh
Labels: 📟 client

#3270 Add version info to the node's header
  cmd/helpers.go
Labels: 📟 client

#3272 TSS pre-params: Fetch pre-params only after symmetric keys are generated
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/member_test.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/dkg/states.go
Labels: 📟 client

#3265 Separate storage classes: `keystore` and `work`
  cmd/flags.go
  cmd/flags_test.go
  cmd/start.go
  config/config.go
  config/config_test.go
  configs/config.toml.SAMPLE
  docs/resources/client-start-help
  docs/resources/client-start-mainnet-sample
  docs/resources/docker-start-mainnet-sample
  docs/resources/docker-start-testnet-sample
  docs/run-keep-node.adoc
  infrastructure/kube/keep-test/keep-client/gen/template.yaml
  infrastructure/kube/keep-test/keep-client/keep-clients.yaml
  pkg/beacon/registry/storage.go
  pkg/storage/storage.go
  test/config.json
  test/config.toml
  test/config.yaml
  test/config_flags.toml
  test/config_mixed_contracts.toml
  test/config_no_contracts.toml
  test/config_no_password.toml
Labels: 📟 client

#3240 Pre params pool size in diagnostics
  cmd/start.go
  pkg/diagnostics/diagnostics.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/dkg/dkg.go
Labels: 📟 client

#3204 Validate Chain ID on ethereum connection establishement
  pkg/chain/ethereum/ethereum.go
Labels: 📟 client

#3260 tECDSA signing: Retries
  pkg/chain/ethereum/beacon.go
  pkg/chain/ethereum/tbtc.go
  pkg/tbtc/dkg.go
  pkg/tbtc/dkg_test.go
  pkg/tbtc/node.go
  pkg/tbtc/signing.go
  pkg/tbtc/signing_test.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/retry/retry.go
  pkg/tecdsa/signing/signing.go
Labels: 📟 client

#3267 tECDSA signing: Context logging
  pkg/generator/pool.go
  pkg/protocol/group/membership_validator.go
  pkg/protocol/group/message_filter.go
  pkg/protocol/state/machine.go
  pkg/tbtc/dkg.go
  pkg/tbtc/node.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/preparams.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/signing.go
Labels: 📟 client

#3273 TSS pre-params: Do not start tECDSA DKG if TSS pre-params pool is too small
  pkg/tbtc/node.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/dkg/dkg.go
Labels: 📟 client

#3271 tECDSA signing: Address all outstanding review comments
  pkg/tecdsa/dkg/gen/pb/message.pb.go
  pkg/tecdsa/dkg/gen/pb/message.proto
  pkg/tecdsa/dkg/marshaling.go
  pkg/tecdsa/dkg/marshaling_test.go
  pkg/tecdsa/dkg/message.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/signature.go
  pkg/tecdsa/signing/gen/pb/message.pb.go
  pkg/tecdsa/signing/gen/pb/message.proto
  pkg/tecdsa/signing/marshaling.go
  pkg/tecdsa/signing/marshaling_test.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/protocol_test.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3274 TSS pre-params: Do not join the sortition pool if TSS pre-params pool is too small
  pkg/beacon/beacon.go
  pkg/sortition/sortition.go
  pkg/sortition/sortition_test.go
  pkg/tbtc/tbtc.go
Labels: 📟 client

#3281 tECDSA DKG: Do not bump blocks delay every 100 attempts
  pkg/tbtc/dkg.go
  pkg/tbtc/dkg_test.go
  pkg/tbtc/signing.go
Labels: 📟 client

#3247 Store generated TSS PreParams on disk
  Dockerfile
  cmd/start.go
  go.mod
  go.sum
  pkg/beacon/beacon.go
  pkg/beacon/registry/groups.go
  pkg/beacon/registry/groups_test.go
  pkg/beacon/registry/storage.go
  pkg/generator/pool.go
  pkg/generator/pool_test.go
  pkg/storage/storage.go
  pkg/tbtc/node.go
  pkg/tbtc/registry.go
  pkg/tbtc/registry_test.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/gen/pb/preparams.pb.go
  pkg/tecdsa/dkg/gen/pb/preparams.proto
  pkg/tecdsa/dkg/marshaling.go
  pkg/tecdsa/dkg/marshaling_test.go
  pkg/tecdsa/dkg/preparams.go
Labels: 📟 client

#3287 Validate PreParams recovered from a file
  pkg/tecdsa/dkg/gen/pb/preparams.pb.go
  pkg/tecdsa/dkg/gen/pb/preparams.proto
  pkg/tecdsa/dkg/marshaling.go
  pkg/tecdsa/dkg/marshaling_test.go
  pkg/tecdsa/dkg/preparams.go
Labels: 📟 client

#3288 Mock WalletRegistry with RandomBeacon
  pkg/chain/ethereum/tbtc.go
Labels: 📟 client

#3289 Reduce number of nodes running in keep-test
  infrastructure/kube/keep-test/keep-client/gen/data.yaml
  infrastructure/kube/keep-test/keep-client/keep-clients.yaml
Labels: :cloud: infrastructure

#3284 Add P2P.ORG bootstrap node
  config/_peers/goerli
Labels: :cloud: infrastructure, 📟 client

#3285 Add kraken/staked goerli testnet validator to bootstrap peers
  config/_peers/goerli
Labels: :cloud: infrastructure, 📟 client

#3295 Do not copy the lock value in broadcast channel
  pkg/net/libp2p/channel.go
Labels: 📟 client

#3296 Pre-param metrics
  cmd/start.go
  docs/resources/client-start-help
  pkg/generator/pool.go
  pkg/generator/pool_test.go
  pkg/metrics/metrics.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/dkg/dkg.go
Labels: 📟 client

#3298 Set network properties for bootstrap nodes
  infrastructure/kube/keep-test/keep-client/gen/data.yaml
  infrastructure/kube/keep-test/keep-client/gen/schema.yaml
  infrastructure/kube/keep-test/keep-client/gen/template.yaml
  infrastructure/kube/keep-test/keep-client/keep-clients.yaml
Labels: :cloud: infrastructure

#3256 Exempt bootstrap nodes from firewall validation
  cmd/flags.go
  cmd/flags_test.go
  cmd/start.go
  configs/config.toml.SAMPLE
  pkg/beacon/beacon.go
  pkg/firewall/firewall.go
  pkg/firewall/firewall_test.go
  pkg/net/libp2p/libp2p.go
  pkg/net/libp2p/libp2p_test.go
  pkg/tbtc/tbtc.go
Labels: 📟 client

#3304 Updated bnb-chain/tss-lib dependency to v1.3.5
  go.mod
  go.sum
Labels: 📟 client

#3255 Query bootstrap node
  pkg/diagnostics/diagnostics.go
  pkg/net/libp2p/libp2p.go
  pkg/net/local/local.go
  pkg/net/net.go
Labels: 📟 client

#3309 Reconfigure keep-test nodes
  infrastructure/kube/keep-test/keep-client/gen/data.yaml
  infrastructure/kube/keep-test/keep-client/gen/template.yaml
  infrastructure/kube/keep-test/keep-client/keep-clients.yaml
Labels: :cloud: infrastructure

#3310 Merge diagnostics and metrics into a single clientinfo registry
  cmd/flags.go
  cmd/flags_test.go
  cmd/start.go
  config/category.go
  config/config.go
  config/config_test.go
  docs/resources/client-start-help
  docs/resources/docker-start-mainnet-sample
  docs/resources/docker-start-testnet-sample
  docs/run-keep-node.adoc
  go.mod
  go.sum
  infrastructure/kube/keep-test/keep-client/gen/template.yaml
  infrastructure/kube/keep-test/keep-client/keep-clients.yaml
  infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/keep-client-config-template.toml
  pkg/clientinfo/clientinfo.go
  pkg/clientinfo/diagnostics.go
  pkg/clientinfo/metrics.go
  pkg/tbtc/tbtc.go
  test/config.json
  test/config.toml
  test/config.yaml
  test/config_flags.toml
Labels: 📟 client

#3313 Improvements to client info metrics and diagnostics
  cmd/start.go
  pkg/beacon/node.go
  pkg/clientinfo/diagnostics.go
  pkg/clientinfo/metrics.go
  pkg/tbtc/node.go
Labels: 📟 client

#3300 Bootstrap node: skip initializing Beacon and Tbtc
  cmd/start.go
  pkg/beacon/beacon.go
  pkg/tbtc/tbtc.go
Labels: 📟 client

#3317 Deployments scripts for mainnet
  solidity/ecdsa/.gitignore
  solidity/ecdsa/.prettierignore
  solidity/ecdsa/deploy/01_deploy_ecdsa_sortition_pool.ts
  solidity/ecdsa/deploy/03_deploy_wallet_registry.ts
  solidity/ecdsa/deploy/04_approve_wallet_registry.ts
  solidity/ecdsa/deploy/10_authorize_in_random_beacon.ts
  solidity/ecdsa/deploy/11_transfer_reimbursement_pool_ownerhsip.ts
  solidity/ecdsa/external/mainnet/T.json
  solidity/ecdsa/external/mainnet/TokenStaking.json
  solidity/ecdsa/hardhat.config.ts
  solidity/random-beacon/.gitignore
  solidity/random-beacon/.prettierignore
  solidity/random-beacon/deploy/02_deploy_beacon_sortition_pool.ts
  solidity/random-beacon/deploy/04_deploy_random_beacon.ts
  solidity/random-beacon/deploy/05_approve_random_beacon_in_token_staking.ts
  solidity/random-beacon/deploy/06_authorize_random_beacon_in_reimbursement_pool.ts
  solidity/random-beacon/external/mainnet/T.json
  solidity/random-beacon/external/mainnet/TokenStaking.json
  solidity/random-beacon/hardhat.config.ts
Labels: ⛓chain

#3316 Beacon DKG: Add message deduplication
  pkg/beacon/gjkr/protocol.go
Labels: 📟 client

#3321 Add session ID to the beacon relay entry messages
  pkg/beacon/entry/entry.go
  pkg/beacon/entry/gen/pb/message.pb.go
  pkg/beacon/entry/gen/pb/message.proto
  pkg/beacon/entry/marshaling.go
  pkg/beacon/entry/marshaling_test.go
  pkg/beacon/entry/message.go
  pkg/beacon/integration_test.go
Labels: 📟 client

#3323 Put beacon DKG execution in right context
  pkg/beacon/dkg/dkg.go
  pkg/beacon/dkg/result/publish.go
  pkg/beacon/dkg/result/signing.go
  pkg/beacon/dkg/result/submission.go
  pkg/beacon/gjkr/gjkr.go
  pkg/beacon/gjkr/member.go
  pkg/beacon/gjkr/protocol.go
  pkg/beacon/node.go
Labels: 📟 client

#3325 Update metrics and diagnostics to clientinfo in config sample
  configs/config.toml.SAMPLE
Labels: 📟 client

#3328 Leaving the default authorization decrease delay of 45 days
  solidity/ecdsa/deploy/03_deploy_wallet_registry.ts
  solidity/random-beacon/deploy/04_deploy_random_beacon.ts
Labels: ⛓chain

#3327 Add session ID to the beacon DKG messages
  pkg/beacon/dkg/dkg.go
  pkg/beacon/dkg/result/gen/pb/message.pb.go
  pkg/beacon/dkg/result/gen/pb/message.proto
  pkg/beacon/dkg/result/marshalling.go
  pkg/beacon/dkg/result/marshalling_test.go
  pkg/beacon/dkg/result/message.go
  pkg/beacon/dkg/result/publish.go
  pkg/beacon/dkg/result/signing.go
  pkg/beacon/dkg/result/signing_test.go
  pkg/beacon/dkg/result/states.go
  pkg/beacon/gjkr/gen/pb/message.pb.go
  pkg/beacon/gjkr/gen/pb/message.proto
  pkg/beacon/gjkr/gjkr.go
  pkg/beacon/gjkr/marshaling.go
  pkg/beacon/gjkr/marshaling_test.go
  pkg/beacon/gjkr/member.go
  pkg/beacon/gjkr/message.go
  pkg/beacon/gjkr/message_filter_test.go
  pkg/beacon/gjkr/message_test.go
  pkg/beacon/gjkr/protocol.go
  pkg/beacon/gjkr/protocol_accusations_test.go
  pkg/beacon/gjkr/protocol_ecdh_test.go
  pkg/beacon/gjkr/protocol_reconstructions_test.go
  pkg/beacon/gjkr/states.go
Labels: 📟 client

#3237 Unit tests for DKG result signer/submitter
  pkg/chain/local_v1/local.go
  pkg/chain/local_v1/signer.go
  pkg/chain/local_v1/signer_test.go
  pkg/tbtc/chain_test.go
  pkg/tbtc/dkg.go
  pkg/tbtc/dkg_test.go
Labels: 📟 client

#3326 Build linux binaries on debian based Docker image
  Dockerfile
Labels: :cloud: infrastructure, 📟 client

#3332 Set default TSS pre-params target pool size to 1000
  cmd/flags_test.go
  pkg/tbtc/tbtc.go
Labels: 📟 client

#3334 Ensure the ECDSA DKG result is signed by the quorum of group members
  pkg/tbtc/dkg.go
  pkg/tbtc/dkg_test.go
Labels: 📟 client

#3336 Regenerate contract bindings based on Goerli artifacts
  pkg/chain/ethereum/ecdsa/gen/abi/WalletRegistry.go
  pkg/chain/ethereum/ecdsa/gen/cmd/WalletRegistry.go
  pkg/chain/ethereum/ecdsa/gen/contract/WalletRegistry.go
  pkg/chain/ethereum/tbtc/gen/abi/Bridge.go
  pkg/chain/ethereum/tbtc/gen/cmd/Bridge.go
  pkg/chain/ethereum/tbtc/gen/contract/Bridge.go
Labels: 📟 client

#3337 Tweak testnet clients Kubernetes manifests
  infrastructure/kube/keep-test/keep-client/gen/template.yaml
  infrastructure/kube/keep-test/keep-client/keep-clients.yaml
Labels: :cloud: infrastructure, 📟 client
