Repository keep-network/keep-core, pull requests merged in 2022-10, with the labels that each got.

#3339 Log tweaks
  pkg/beacon/node.go
  pkg/sortition/sortition.go
  pkg/tbtc/node.go
Labels: 📟 client

#3338 Client build mainnet
  Makefile
  cmd/flags_test.go
  pkg/chain/ethereum/tbtc/gen/gen.go
Labels: 📟 client

#3342 Made keep-client exclude own address from bootstrap peer list
  pkg/net/libp2p/libp2p.go
Labels: 📟 client

#3350 Run cmd-help after release when making all
  Makefile
Labels: 📟 client

#3347 ECDSA DKG: Add confirmation state at the end of the protocol
  pkg/tecdsa/dkg/dkg.go
  pkg/tecdsa/dkg/gen/pb/message.pb.go
  pkg/tecdsa/dkg/gen/pb/message.proto
  pkg/tecdsa/dkg/marshaling.go
  pkg/tecdsa/dkg/marshaling_test.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/message.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/protocol_test.go
  pkg/tecdsa/dkg/states.go
Labels: 📟 client

#3353 Monitoring for keep-test
  infrastructure/kube/keep-test/monitoring/README.adoc
  infrastructure/kube/keep-test/monitoring/grafana/config/dashboards.yaml
  infrastructure/kube/keep-test/monitoring/grafana/config/datasources.yaml
  infrastructure/kube/keep-test/monitoring/grafana/dashboards/keep-network-nodes-dashboard.json
  infrastructure/kube/keep-test/monitoring/grafana/dashboards/prometheus.json
  infrastructure/kube/keep-test/monitoring/grafana/grafana-deployment.yaml
  infrastructure/kube/keep-test/monitoring/grafana/grafana-pvc.yaml
  infrastructure/kube/keep-test/monitoring/grafana/grafana-service.yaml
  infrastructure/kube/keep-test/monitoring/grafana/kustomization.yaml
  infrastructure/kube/keep-test/monitoring/monitoring-ingress.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/config/config.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/config/external-clients-targets.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/config/rules.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/kustomization.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/prometheus-cluster-role.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/prometheus-deployment.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/prometheus-pvc.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/prometheus-service.yaml
  infrastructure/kube/keep-test/monitoring/storage-class.yaml
Labels: :cloud: infrastructure

#3356 Logging fixes
  pkg/beacon/dkg/result/signing.go
  pkg/tbtc/tbtc.go
  pkg/tecdsa/dkg/protocol.go
Labels: 📟 client

#3357 keep-test: Monitoring - define Ingress to expose Grafana publicly
  infrastructure/kube/keep-test/monitoring/README.adoc
  infrastructure/kube/keep-test/monitoring/grafana/config/dashboards.yaml
  infrastructure/kube/keep-test/monitoring/grafana/config/datasources.yaml
  infrastructure/kube/keep-test/monitoring/grafana/config/grafana.ini
  infrastructure/kube/keep-test/monitoring/grafana/dashboards/infrastructure/kubernetes-deployments.json
  infrastructure/kube/keep-test/monitoring/grafana/dashboards/keep/keep-network-nodes-public.json
  infrastructure/kube/keep-test/monitoring/grafana/dashboards/keep/keep-network-nodes.json
  infrastructure/kube/keep-test/monitoring/grafana/grafana-deployment.yaml
  infrastructure/kube/keep-test/monitoring/grafana/grafana-service.yaml
  infrastructure/kube/keep-test/monitoring/grafana/kustomization.yaml
  infrastructure/kube/keep-test/monitoring/monitoring-ingress.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/config/config.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/config/rules.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/prometheus-deployment.yaml
  infrastructure/kube/keep-test/monitoring/trickster/config/trickster.yaml
  infrastructure/kube/keep-test/monitoring/trickster/kustomization.yaml
  infrastructure/kube/keep-test/monitoring/trickster/trickster-deployment.yaml
  infrastructure/kube/keep-test/monitoring/trickster/trickster-service.yaml
Labels: :cloud: infrastructure

#3362 Fast state machine
  pkg/net/local/broadcast_channel.go
  pkg/net/local/broadcast_channel_test.go
  pkg/protocol/faststate/faststate.go
  pkg/protocol/faststate/faststate_test.go
  pkg/protocol/faststate/machine.go
  pkg/protocol/faststate/machine_test.go
  pkg/protocol/state/machine.go
  pkg/protocol/state/state.go
Labels: 📟 client

#3361 tECDSA signing: Announcement phase
  pkg/tbtc/gen/pb/message.pb.go
  pkg/tbtc/gen/pb/message.proto
  pkg/tbtc/gen/pb/stop.pb.go
  pkg/tbtc/gen/pb/stop.proto
  pkg/tbtc/node.go
  pkg/tbtc/signing.go
  pkg/tbtc/signing_test.go
Labels: 📟 client

#3363 Do not wait on writing to pool if the context got canceled
  pkg/generator/pool.go
  pkg/generator/pool_test.go
Labels: 📟 client

#3373 keep-test monitoring - expose prometheus
  infrastructure/kube/keep-test/monitoring/README.adoc
  infrastructure/kube/keep-test/monitoring/grafana/config/datasources.yaml
  infrastructure/kube/keep-test/monitoring/grafana/grafana-deployment.yaml
  infrastructure/kube/keep-test/monitoring/monitoring-ingress.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/prometheus-deployment.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/prometheus-service.yaml
  infrastructure/kube/keep-test/monitoring/trickster/config/trickster.yaml
  infrastructure/kube/keep-test/monitoring/trickster/trickster-deployment.yaml
  infrastructure/kube/keep-test/monitoring/trickster/trickster-service.yaml
Labels: :cloud: infrastructure

#3375 Monitoring configuration for production
  infrastructure/kube/keep-prd/monitoring/README.adoc
  infrastructure/kube/keep-prd/monitoring/grafana/config/dashboards.yaml
  infrastructure/kube/keep-prd/monitoring/grafana/config/datasources.yaml
  infrastructure/kube/keep-prd/monitoring/grafana/config/grafana.ini
  infrastructure/kube/keep-prd/monitoring/grafana/dashboards/keep/keep-nodes-public.json
  infrastructure/kube/keep-prd/monitoring/grafana/dashboards/keep/keep-nodes.json
  infrastructure/kube/keep-prd/monitoring/grafana/grafana-deployment.yaml
  infrastructure/kube/keep-prd/monitoring/grafana/grafana-pvc.yaml
  infrastructure/kube/keep-prd/monitoring/grafana/grafana-service.yaml
  infrastructure/kube/keep-prd/monitoring/grafana/kustomization.yaml
  infrastructure/kube/keep-prd/monitoring/monitoring-ingress.yaml
  infrastructure/kube/keep-prd/monitoring/prometheus/config/config.yaml
  infrastructure/kube/keep-prd/monitoring/prometheus/kustomization.yaml
  infrastructure/kube/keep-prd/monitoring/prometheus/prometheus-deployment.yaml
  infrastructure/kube/keep-prd/monitoring/prometheus/prometheus-pvc.yaml
  infrastructure/kube/keep-prd/monitoring/prometheus/prometheus-service.yaml
  infrastructure/kube/keep-prd/monitoring/storage-class.yaml
  infrastructure/kube/keep-prd/monitoring/trickster/config/trickster.yaml
  infrastructure/kube/keep-prd/monitoring/trickster/kustomization.yaml
  infrastructure/kube/keep-prd/monitoring/trickster/trickster-deployment.yaml
  infrastructure/kube/keep-prd/monitoring/trickster/trickster-service.yaml
Labels: :cloud: infrastructure

#3379 tECDSA signing: Integration with the asynchronous state machine
  pkg/net/net.go
  pkg/net/retransmission/retransmission.go
  pkg/protocol/state/async_machine.go
  pkg/protocol/state/async_machine_test.go
  pkg/tbtc/node.go
  pkg/tbtc/signing.go
  pkg/tbtc/signing_test.go
  pkg/tecdsa/signing/message.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
  pkg/tecdsa/signing/states_test.go
Labels: 📟 client

#3282 Document deployments and contracts addresses
  docs/index.adoc
  docs/registration.adoc
  docs/run-keep-node.adoc
Labels: :book: documentation

#3383 Assign each retransmission request a unique id
  pkg/net/net.go
  pkg/net/retransmission/retransmission.go
  pkg/net/retransmission/ticker.go
  pkg/net/retransmission/ticker_test.go
  pkg/tecdsa/signing/errors.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3385 Asynchronous state machine: do not block on state initiation
  pkg/protocol/state/async_machine.go
  pkg/protocol/state/async_machine_test.go
  pkg/protocol/state/state.go
  pkg/tecdsa/signing/signing.go
  pkg/tecdsa/signing/states.go
  pkg/tecdsa/signing/states_test.go
Labels: 📟 client

#3386 Abstract common patterns used within tECDSA signing
  pkg/protocol/state/state.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3388 Identify stop pill by DKG seed or signed message
  pkg/tbtc/gen/pb/message.pb.go
  pkg/tbtc/gen/pb/message.proto
  pkg/tbtc/node.go
  pkg/tbtc/stop.go
Labels: 📟 client

#3389 Increase scan timeout to 3 seconds
  infrastructure/kube/keep-prd/monitoring/prometheus/prometheus-deployment.yaml
  infrastructure/kube/keep-test/monitoring/prometheus/prometheus-deployment.yaml
Labels: :cloud: infrastructure
