Repository keep-network/keep-core, pull requests merged in 2022-12, with the labels that each got.

#3425 DKG saga, part 1: Extracted dkgExecutor logic out of the node structure
  pkg/tbtc/dkg.go
  pkg/tbtc/dkg_loop.go
  pkg/tbtc/dkg_loop_test.go
  pkg/tbtc/dkg_submit.go
  pkg/tbtc/dkg_submit_test.go
  pkg/tbtc/dkg_test.go
  pkg/tbtc/node.go
  pkg/tbtc/tbtc.go
Labels: 📟 client

#3428 DKG saga, part 3: Adjusted the memberID / memberIndex nomenclature
  pkg/beacon/dkg/dkg.go
  pkg/beacon/dkg/dkg_test.go
  pkg/beacon/dkg/result/conversion.go
  pkg/beacon/dkg/result/conversion_test.go
  pkg/beacon/gjkr/member.go
  pkg/beacon/gjkr/protocol.go
  pkg/beacon/gjkr/protocol_accusations_test.go
  pkg/beacon/gjkr/protocol_reconstructions_test.go
  pkg/protocol/group/group.go
  pkg/protocol/group/group_test.go
  pkg/protocol/group/message_filter.go
  pkg/protocol/group/message_filter_test.go
  pkg/tbtc/dkg.go
  pkg/tbtc/dkg_test.go
  pkg/tecdsa/dkg/member.go
  pkg/tecdsa/dkg/protocol.go
  pkg/tecdsa/dkg/result.go
  pkg/tecdsa/dkg/states.go
  pkg/tecdsa/signing/member.go
  pkg/tecdsa/signing/protocol.go
  pkg/tecdsa/signing/states.go
Labels: 📟 client

#3440 Split the signing done check into a listen and a wait phases
  pkg/tbtc/signing_done.go
  pkg/tbtc/signing_done_test.go
  pkg/tbtc/signing_loop.go
  pkg/tbtc/signing_loop_test.go
Labels: 📟 client

#3406 Electrum integration for Bitcoin chain
  cmd/flags.go
  cmd/flags_test.go
  cmd/tbtc_maintainer.go
  config/config.go
  config/config_test.go
  configs/config.toml.SAMPLE
  go.mod
  go.sum
  pkg/bitcoin/chain.go
  pkg/bitcoin/electrum/block.go
  pkg/bitcoin/electrum/config.go
  pkg/bitcoin/electrum/electrum.go
  pkg/bitcoin/electrum/electrum_integration_test.go
  pkg/bitcoin/electrum/flag.go
  pkg/bitcoin/electrum/protocol.go
  pkg/bitcoin/electrum/protocol_test.go
  pkg/bitcoin/electrum/transaction.go
  pkg/bitcoin/hash.go
  pkg/bitcoin/hash_test.go
  pkg/internal/byteutils/byteutils.go
  pkg/internal/byteutils/byteutils_test.go
  test/config.json
  test/config.toml
  test/config.yaml
Labels: 📟 client

#3398 Update status badges in READMEs
  README.adoc
  solidity/ecdsa/README.adoc
  solidity/random-beacon/README.adoc
Labels: :book: documentation

#3405 Bitcoin difficulty maintainer: Added LightRelay handle
  cmd/flags.go
  cmd/flags_test.go
  cmd/tbtc_maintainer.go
  config/config_test.go
  config/contracts.go
  pkg/chain/ethereum/bitcoin_difficulty.go
  pkg/chain/ethereum/ethereum.go
  pkg/chain/ethereum/tbtc/gen/Makefile
  pkg/chain/ethereum/tbtc/gen/_address/LightRelay
  pkg/chain/ethereum/tbtc/gen/gen.go
  pkg/tbtc/maintainer/chain.go
  test/config.json
  test/config.toml
  test/config.yaml
Labels: 📟 client

#3421 Deposit sweep: Assemble Bitcoin transactions
  pkg/bitcoin/chain_test.go
  pkg/bitcoin/hash.go
  pkg/bitcoin/hash_test.go
  pkg/bitcoin/script.go
  pkg/bitcoin/script_test.go
  pkg/bitcoin/transaction.go
  pkg/bitcoin/transaction_builder.go
  pkg/bitcoin/transaction_builder_test.go
  pkg/bitcoin/transaction_test.go
  pkg/internal/tbtctest/marshaling.go
  pkg/internal/tbtctest/tbtctest.go
  pkg/internal/tbtctest/testdata/deposit_sweep_scenario_0.json
  pkg/internal/tbtctest/testdata/deposit_sweep_scenario_1.json
  pkg/internal/tbtctest/testdata/deposit_sweep_scenario_2.json
  pkg/internal/tbtctest/testdata/deposit_sweep_scenario_3.json
  pkg/tbtc/deposit.go
  pkg/tbtc/deposit_sweep.go
  pkg/tbtc/deposit_sweep_test.go
  pkg/tbtc/deposit_test.go
  pkg/tecdsa/key.go
Labels: 📟 client

#3445 Upgrade version of Node used in CI to v18
  .github/workflows/contracts-random-beacon.yml
  .github/workflows/npm-random-beacon.yml
  solidity/random-beacon/package.json
  solidity/random-beacon/yarn.lock
Labels: :cloud: infrastructure

#3449 Fix badges after change in shields.io syntax
  README.adoc
  solidity/ecdsa/README.adoc
  solidity/random-beacon/README.adoc
Labels: :book: documentation

#3452 Upgrade version of Node used in CI to `v18`
  .github/workflows/contracts-ecdsa.yml
  .github/workflows/npm-ecdsa.yml
  solidity/ecdsa/package.json
  solidity/ecdsa/yarn.lock
Labels: dependencies

#3454 Change SemVer range for `@tenderly/hardhat-tenderly` dependency
  solidity/ecdsa/package.json
  solidity/ecdsa/yarn.lock
  solidity/random-beacon/package.json
  solidity/random-beacon/yarn.lock
Labels: :shipit: deployment

#3394 Bitcoin difficulty maintainer: Logic
  cmd/cmd.go
  cmd/flags.go
  cmd/flags_test.go
  cmd/maintainer.go
  config/category.go
  config/config.go
  config/config_test.go
  pkg/maintainer/bitcoin_chain_test.go
  pkg/maintainer/bitcoin_difficulty.go
  pkg/maintainer/bitcoin_difficulty_test.go
  pkg/maintainer/chain.go
  pkg/maintainer/chain_test.go
  pkg/maintainer/config.go
  pkg/maintainer/maintainer.go
  pkg/tbtc/maintainer/bitcoin_difficulty.go
  pkg/tbtc/maintainer/chain.go
  pkg/tbtc/tbtc.go
  test/config.json
  test/config.toml
  test/config.yaml
Labels: 📟 client

#3444 Block header serialization
  pkg/bitcoin/block.go
  pkg/bitcoin/block_test.go
Labels: 📟 client

#3402 Adding RandomBeaconChaosnet contract
  solidity/random-beacon/contracts/RandomBeaconChaosnet.sol
  solidity/random-beacon/contracts/test/RandomBeaconChaosnetStub.sol
  solidity/random-beacon/deploy/09_deploy_random_beacon_chaosnet.ts
  solidity/random-beacon/test/RandomBeaconChaosnet.Callback.test.ts
Labels: :chains: solidity
