Repository keep-network/keep-core, pull requests merged in 2022-07, with the labels that each got.

#3032 Update libp2p modules
  go.mod
  go.sum
  pkg/net/libp2p/authenticated_connection_test.go
  pkg/net/libp2p/key.go
  pkg/net/libp2p/key_test.go
  pkg/net/libp2p/libp2p.go
  pkg/net/libp2p/transport.go
Labels: 📟 client

#3056 Interface and local implementation for sortition chain
  pkg/chain/chain.go
  pkg/internal/testutils/testutils.go
  pkg/sortition/chain.go
  pkg/sortition/internal/local.go
  pkg/sortition/internal/local_test.go
Labels: 📟 client

#3063 Prepare deployment artifacts for contracts packages publication
  .github/workflows/npm-ecdsa.yml
  .github/workflows/npm-random-beacon.yml
  solidity/ecdsa/package.json
  solidity/ecdsa/yarn.lock
  solidity/random-beacon/package.json
  solidity/random-beacon/yarn.lock
Labels: ⛓chain

#3034 DKG test loop
  cmd/start.go
  pkg/beacon/beacon.go
  pkg/beacon/relay/chain/chain.go
  pkg/beacon/relay/chain/group_ticket.go
  pkg/beacon/relay/event/deduplicator.go
  pkg/beacon/relay/event/deduplicator_test.go
  pkg/beacon/relay/event/event.go
  pkg/beacon/relay/groupselection/groupselection.go
  pkg/beacon/relay/groupselection/groupselection_test.go
  pkg/beacon/relay/groupselection/ticket.go
  pkg/beacon/relay/groupselection/ticket_generate.go
  pkg/beacon/relay/groupselection/ticket_generate_test.go
  pkg/beacon/relay/groupselection/ticket_sort.go
  pkg/beacon/relay/groupselection/ticket_sort_test.go
  pkg/beacon/relay/groupselection/ticket_submission.go
  pkg/beacon/relay/groupselection/ticket_submission_test.go
  pkg/beacon/relay/node.go
  pkg/beacon/relay/registry/groups_test.go
  pkg/chain/ethereum/connect.go
  pkg/chain/ethereum/ethereum.go
  pkg/chain/ethereum/ethereum_test.go
  pkg/chain/local/local.go
  pkg/chain/local/local_test.go
  pkg/chain/staker.go
  pkg/gen/async.go
  pkg/gen/async/event_group_ticket_submission_promise.go
Labels: 📟 client

#3064 Updated bootstrap address in config.toml.SAMPLE
  configs/config.toml.SAMPLE
Labels: 📟 client

#3067 RandomBeacon contract for the Beacon Ethereum chain - sortition functions
  pkg/chain/ethereum/beacon.go
  pkg/chain/ethereum/ethereum.go
  pkg/chain/ethereum/tbtc.go
  pkg/sortition/chain.go
Labels: 📟 client

#3066 Added padding for operator private keys shorter than 32 bytes
  pkg/net/libp2p/key.go
  pkg/net/libp2p/key_test.go
Labels: 📟 client

#3073 Upgrade @threshold-network/solidity-contracts in beacon
  .github/workflows/npm-random-beacon.yml
  solidity/random-beacon/yarn.lock
Labels: ⛓chain, :cloud: infrastructure

#3075 Update yarn.lock for ECDSA
  solidity/ecdsa/yarn.lock
Labels: ⛓chain

#3070 IsOperatorUpToDate and UpdateOperatorStatus functions added to sortition Chain
  pkg/chain/ethereum/beacon.go
  pkg/sortition/chain.go
  pkg/sortition/internal/local.go
  pkg/sortition/internal/local_test.go
Labels: 📟 client

#3071 Update expected artifacts for generation
  pkg/chain/common/gen/Makefile
  pkg/chain/ecdsa/gen/Makefile
  pkg/chain/ecdsa/gen/abi/EcdsaSortitionPool.go
  pkg/chain/ecdsa/gen/cmd/EcdsaSortitionPool.go
  pkg/chain/ecdsa/gen/contract/EcdsaSortitionPool.go
  pkg/chain/ethereum/beacon.go
  pkg/chain/random-beacon/gen/Makefile
  pkg/chain/random-beacon/gen/abi/BeaconSortitionPool.go
  pkg/chain/random-beacon/gen/cmd/BeaconSortitionPool.go
  pkg/chain/random-beacon/gen/contract/BeaconSortitionPool.go
Labels: 📟 client

#3050 Drafting docs for local setup
  docs/development/README.adoc
  docs/development/local-t-network.adoc
Labels: 📟 client

#3077 Monitor Random Beacon sortition pool status: join pool and update pool
  cmd/start.go
  configs/config.toml.SAMPLE
  pkg/beacon/beacon.go
  pkg/sortition/internal/local.go
  pkg/sortition/internal/local/chain.go
  pkg/sortition/internal/local/chain_test.go
  pkg/sortition/sortition.go
  pkg/sortition/sortition_test.go
Labels: 📟 client

#3029 ECDSA: Improve validation of new wallet's public key
  solidity/ecdsa/contracts/WalletRegistry.sol
  solidity/ecdsa/contracts/libraries/Wallets.sol
  solidity/ecdsa/contracts/test/WalletRegistryStub.sol
  solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2.sol
  solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2MisplacedNewSlot.sol
  solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2MissingSlot.sol
  solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts
Labels: 🔒security, ⛓chain

#3086 Extract contract addresses from artifacts
  .github/workflows/client.yml
  .gitignore
  Dockerfile
  go.sum
  pkg/chain/ethereum/beacon/gen/_address/.keep
  pkg/chain/ethereum/beacon/gen/gen.go
  pkg/chain/ethereum/common/gen/Makefile
  pkg/chain/ethereum/ecdsa/gen/_address/.keep
  pkg/chain/ethereum/ecdsa/gen/gen.go
  pkg/chain/ethereum/tbtc/gen/_address/.keep
  pkg/chain/ethereum/tbtc/gen/gen.go
  pkg/chain/ethereum/threshold/gen/_address/.keep
  pkg/chain/ethereum/threshold/gen/gen.go
Labels: 📟 client

#3085 Rewards eligibility checks for an operator
  pkg/chain/ethereum/beacon.go
  pkg/chain/ethereum/beacon/gen/abi/BeaconSortitionPool.go
  pkg/chain/ethereum/beacon/gen/cmd/BeaconSortitionPool.go
  pkg/chain/ethereum/beacon/gen/contract/BeaconSortitionPool.go
  pkg/chain/ethereum/ecdsa/gen/abi/EcdsaSortitionPool.go
  pkg/chain/ethereum/ecdsa/gen/cmd/EcdsaSortitionPool.go
  pkg/chain/ethereum/ecdsa/gen/contract/EcdsaSortitionPool.go
  pkg/chain/local_v1/local.go
  pkg/sortition/chain.go
  pkg/sortition/internal/local/chain.go
  pkg/sortition/internal/local/chain_test.go
  pkg/sortition/sortition.go
  pkg/sortition/sortition_test.go
Labels: 📟 client

#3088 Relay entry test loop: Actual logic
  pkg/beacon/beacon_test.go
  pkg/beacon/chain/chain.go
  pkg/beacon/dkg/dkg.go
  pkg/beacon/dkg/dkg_test.go
  pkg/beacon/dkg/marshalling.go
  pkg/beacon/dkg/marshalling_test.go
  pkg/beacon/dkg/signer.go
  pkg/beacon/entry/submission.go
  pkg/beacon/entry/submission_test.go
  pkg/beacon/event/event.go
  pkg/beacon/group/membership_validator.go
  pkg/beacon/group/membership_validator_test.go
  pkg/beacon/node.go
  pkg/beacon/node_test.go
  pkg/beacon/registry/gen/pb/message.pb.go
  pkg/beacon/registry/gen/pb/message.proto
  pkg/beacon/registry/groups_test.go
  pkg/beacon/registry/marshalling_test.go
  pkg/chain/ethereum/beacon.go
  pkg/chain/local_v1/local.go
  pkg/chain/local_v1/local_test.go
  pkg/gen/async.go
  pkg/gen/async/.keep
  pkg/gen/async/event_group_registration_promise.go
  pkg/gen/async/event_relay_entry_requested_promise.go
  pkg/gen/async/event_relay_entry_submitted_promise.go
  pkg/internal/dkgtest/dkgtest.go
Labels: 📟 client

#3089 3012 Prepare Geth node for Goerli Network on K8S
  infrastructure/kube/keep-test/geth-node/eth-goerli-node.yaml
Labels: :cloud: infrastructure

#3095 Upgrading hardhat helpers to 0.6.0-pre.10
  solidity/ecdsa/package.json
  solidity/ecdsa/yarn.lock
Labels: 📟 client

#3094 ECDSA sortition pool registration
  pkg/chain/ethereum/tbtc.go
  pkg/tbtc/tbtc.go
Labels: 📟 client

#3109 One More Once: Signing Retry Algorithm
  pkg/ecdsa/retry/retry.go
  pkg/ecdsa/retry/retry_test.go
Labels: 📟 client

#3030 Beacon: Improve validation of new group's public key
  solidity/ecdsa/contracts/libraries/Wallets.sol
  solidity/random-beacon/contracts/RandomBeacon.sol
  solidity/random-beacon/contracts/libraries/Groups.sol
  solidity/random-beacon/contracts/test/GroupsStub.sol
  solidity/random-beacon/test/Groups.test.ts
  solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
  solidity/random-beacon/test/fixtures/index.ts
Labels: 🔒security, ⛓chain

#3117 Rolled back the needed check during DKG submission
  pkg/chain/ethereum/beacon.go
Labels: 📟 client
