Repository keep-network/keep-core, pull requests merged in 2023-05, with the labels that each got.

#3546 Add missing `BitcoinElectrum` flag category for `start` command
  config/category.go
Labels: 📟 client

#3547 Make prometheus internally exposed on keep-test
  infrastructure/kube/keep-test/monitoring/monitoring-ingress.yaml
Labels: :cloud: infrastructure

#3548 Connect `keep-test` clients to testnet ElectrumX instance
  infrastructure/kube/keep-test/keep-client/gen/template.yaml
  infrastructure/kube/keep-test/keep-client/keep-client-config.yaml
  infrastructure/kube/keep-test/keep-client/keep-clients.yaml
Labels: 📟 client

#3535 Bitcoin difficulty maintainer logic update
  cmd/flags.go
  cmd/flags_test.go
  cmd/maintainer.go
  config/config_test.go
  pkg/chain/ethereum/bitcoin_difficulty.go
  pkg/chain/ethereum/ethereum.go
  pkg/maintainer/bitcoin_difficulty.go
  pkg/maintainer/bitcoin_difficulty_test.go
  pkg/maintainer/chain.go
  pkg/maintainer/chain_test.go
  pkg/maintainer/config.go
  pkg/maintainer/maintainer.go
  test/config.json
  test/config.toml
  test/config.yaml
Labels: 📟 client

#3550 Leverage deposits reveal blocks passed within the sweep proposal
  pkg/chain/ethereum/tbtc.go
  pkg/chain/ethereum/tbtc/gen/abi/WalletCoordinator.go
  pkg/tbtc/chain.go
  pkg/tbtc/chain_test.go
  pkg/tbtc/deposit_sweep.go
  pkg/tbtc/deposit_sweep_test.go
Labels: 📟 client

#3551 Fix deposit script function
  pkg/tbtc/deposit.go
Labels: 📟 client

#3552 Deposit sweep log tweaks
  pkg/tbtc/deposit_sweep.go
  pkg/tbtc/signing.go
Labels: 📟 client

#3553 Fix broadcast function in Electrum implementation
  pkg/bitcoin/electrum/electrum.go
Labels: 📟 client

#3545 CLI command to list tBTC deposits
  cmd/cmd.go
  cmd/coordinator.go
  pkg/chain/ethereum/tbtc.go
  pkg/coordinator/coordinator.go
  pkg/coordinator/deposits.go
  pkg/internal/hexutils/hexutils.go
  pkg/internal/hexutils/hexutils_test.go
  pkg/tbtc/chain.go
  pkg/tbtc/chain_test.go
Labels: 📟 client

#3555 P2P bootstrap nodes for mainnet
  config/_peers/mainnet
Labels: 📟 client

#3541 Heartbea(s)t III: Trigger heartbeats from WalletCoordinator contract
  docs/resources/client-start-help
  go.mod
  go.sum
  pkg/chain/ethereum/beacon/gen/cmd/BeaconSortitionPool.go
  pkg/chain/ethereum/beacon/gen/cmd/RandomBeacon.go
  pkg/chain/ethereum/ecdsa/gen/cmd/EcdsaSortitionPool.go
  pkg/chain/ethereum/ecdsa/gen/cmd/WalletRegistry.go
  pkg/chain/ethereum/tbtc/gen/abi/Bridge.go
  pkg/chain/ethereum/tbtc/gen/cmd/Bridge.go
  pkg/chain/ethereum/tbtc/gen/cmd/LightRelay.go
  pkg/chain/ethereum/tbtc/gen/cmd/WalletCoordinator.go
  pkg/chain/ethereum/tbtc/gen/contract/Bridge.go
  pkg/chain/ethereum/threshold/gen/cmd/TokenStaking.go
  pkg/internal/testutils/testutils.go
  pkg/tbtc/deposit_sweep.go
  pkg/tbtc/deposit_sweep_test.go
  pkg/tbtc/heartbeat.go
  pkg/tbtc/heartbeat_test.go
  pkg/tbtc/node.go
  pkg/tbtc/registry.go
  pkg/tbtc/tbtc.go
Labels: 📟 client

#3558 Remove pre-signing delay from deposit sweep action
  pkg/tbtc/deposit_sweep.go
  pkg/tbtc/deposit_sweep_test.go
Labels: 📟 client

#3549 CLI command to submit a deposit sweep proposal
  cmd/coordinator.go
  pkg/chain/ethereum/tbtc.go
  pkg/coordinator/deposits.go
  pkg/coordinator/sweep.go
  pkg/internal/hexutils/hexutils_test.go
  pkg/tbtc/chain.go
  pkg/tbtc/chain_test.go
  pkg/tbtc/deposit_sweep.go
Labels: 📟 client

#3559 Ensure wallet BTC state is reflected on the host chain before sweeping
  pkg/bitcoin/chain.go
  pkg/bitcoin/chain_test.go
  pkg/bitcoin/electrum/electrum.go
  pkg/maintainer/bitcoin_chain_test.go
  pkg/tbtc/bitcoin_chain_test.go
  pkg/tbtc/deposit_sweep.go
Labels: 📟 client

#3561 Increase the gas limit for retarget with refund
  pkg/chain/ethereum/bitcoin_difficulty.go
Labels: 📟 client

#3557 Update keep-test Kubernetes deployment for BTC difficulty maintainer
  infrastructure/kube/keep-test/btc-difficulty/config/keep-client-config.toml
  infrastructure/kube/keep-test/btc-difficulty/kustomization.yaml
  infrastructure/kube/keep-test/btc-difficulty/maintainer-statefulset.yaml
Labels: 📟 client

#3567 go-electrum client dependency upgrade
  go.mod
  go.sum
  pkg/bitcoin/electrum/electrum_integration_test.go
Labels: 📟 client

#3570 Pin go-electrum dependency to master branch commit
  go.mod
  go.sum
Labels: 📟 client

#3577 Switch btc-difficulty electrum api url
  infrastructure/kube/keep-prd/btc-difficulty/kustomization.yaml
  infrastructure/kube/keep-prd/btc-difficulty/maintainer-statefulset.yaml
Labels: :cloud: infrastructure

#3575 Client Docker image build command added to the build script
  scripts/build.sh
Labels: 📟 client

#3576 Embed Electrum configs for Bitcoin mainnet and testnet
  cmd/flags.go
  config/_electrum_urls/mainnet
  config/_electrum_urls/testnet
  config/config.go
  config/electrum.go
  config/electrum_test.go
  configs/config.toml.SAMPLE
  pkg/bitcoin/bitcoin.go
Labels: 📟 client

#3542 Keep Dashboard Legacy Warning
  .git-blame-ignore-revs
  solidity-v1/dashboard/package-lock.json
  solidity-v1/dashboard/package.json
  solidity-v1/dashboard/src/App.js
  solidity-v1/dashboard/src/__tests__/saga/rootSaga.test.js
  solidity-v1/dashboard/src/__tests__/saga/tbtc-migration.test.js
  solidity-v1/dashboard/src/actions/coverage-pool.js
  solidity-v1/dashboard/src/actions/index.js
  solidity-v1/dashboard/src/actions/tbtc-migration.js
  solidity-v1/dashboard/src/components/ExternalPoolLiquidityRewardCard.jsx
  solidity-v1/dashboard/src/components/Icons.jsx
  solidity-v1/dashboard/src/components/InactiveButExternalLiquidityRewardCard.jsx
  solidity-v1/dashboard/src/components/InactiveLiquidityRewardCard.jsx
  solidity-v1/dashboard/src/components/Routing.jsx
  solidity-v1/dashboard/src/components/SideMenu.jsx
  solidity-v1/dashboard/src/components/modal/LegacyDashboardModal.jsx
  solidity-v1/dashboard/src/components/modal/ModalRoot.jsx
  solidity-v1/dashboard/src/components/modal/coverage-pools/deposit/InitiateDeposit.jsx
  solidity-v1/dashboard/src/components/modal/coverage-pools/deposit/WarningBeforeDeposit.jsx
  solidity-v1/dashboard/src/components/modal/coverage-pools/deposit/index.js
  solidity-v1/dashboard/src/components/modal/coverage-pools/index.js
  solidity-v1/dashboard/src/components/modal/tbtc-migration/ConfirmMigration.jsx
  solidity-v1/dashboard/src/components/modal/tbtc-migration/MigrationCompleted.jsx
  solidity-v1/dashboard/src/components/modal/tbtc-migration/index.js
  solidity-v1/dashboard/src/components/tbtc-migration/MigrationPortalForm.jsx
  solidity-v1/dashboard/src/components/tbtc-migration/index.js
  solidity-v1/dashboard/src/components/tbtc-migration/styles.js
  solidity-v1/dashboard/src/constants/constants.js
  solidity-v1/dashboard/src/constants/events.js
  solidity-v1/dashboard/src/css/app.less
  solidity-v1/dashboard/src/css/coverage-pools-page.less
  solidity-v1/dashboard/src/css/liquidity-page.less
  solidity-v1/dashboard/src/css/tbtc-migration-page.less
  solidity-v1/dashboard/src/css/vars.less
  solidity-v1/dashboard/src/hooks/useLocalStorage.js
  solidity-v1/dashboard/src/hooks/useShowLegacyDappModal.js
  solidity-v1/dashboard/src/pages/coverage-pools/CoveragePoolPage.jsx
  solidity-v1/dashboard/src/pages/liquidity/LiquidityPage.jsx
  solidity-v1/dashboard/src/pages/liquidity/index.js
  solidity-v1/dashboard/src/pages/tbtc-migration/HowItWorksPage.jsx
  solidity-v1/dashboard/src/pages/tbtc-migration/TokenUpgradePortalPage.jsx
  solidity-v1/dashboard/src/pages/tbtc-migration/index.js
  solidity-v1/dashboard/src/reducers/index.js
  solidity-v1/dashboard/src/reducers/tbtc-migration.js
  solidity-v1/dashboard/src/sagas/coverage-pool.js
  solidity-v1/dashboard/src/sagas/index.js
  solidity-v1/dashboard/src/sagas/liquidity-rewards.js
  solidity-v1/dashboard/src/sagas/subscriptions.js
  solidity-v1/dashboard/src/sagas/tbtc-migration.js
  solidity-v1/dashboard/src/sagas/utils.js
  solidity-v1/dashboard/src/services/liquidity-rewards.js
  solidity-v1/dashboard/src/services/uniswap-api.js
  solidity-v1/dashboard/src/static/svg/legacy-dapp-modal.svg
Labels: :old_key: token dashboard

#3585 Remove tbtc-v2 package from Keep DApp.
  solidity-v1/dashboard/package-lock.json
  solidity-v1/dashboard/package.json
  solidity-v1/dashboard/src/lib/keep/__tests__/tbtc-migration.test.js
  solidity-v1/dashboard/src/lib/keep/contracts/index.js
  solidity-v1/dashboard/src/lib/keep/index.js
  solidity-v1/dashboard/src/lib/keep/tbtc-migration/index.js
Labels: :old_key: token dashboard

#3578 Added GetTransactionMerkle to Electrum client
  internal/testdata/bitcoin/transaction.go
  pkg/bitcoin/chain.go
  pkg/bitcoin/chain_test.go
  pkg/bitcoin/electrum/electrum.go
  pkg/bitcoin/electrum/electrum_integration_test.go
  pkg/bitcoin/electrum/transaction.go
  pkg/bitcoin/transaction.go
  pkg/maintainer/bitcoin_chain_test.go
  pkg/tbtc/bitcoin_chain_test.go
Labels: 📟 client

#3583 Replace flag --goerli with --testnet
  cmd/flags.go
  config/_peers/testnet
  config/config.go
  config/network/network.go
  config/peers.go
  config/peers_test.go
  docs/registration.adoc
  docs/resources/client-start-help
  docs/resources/docker-start-testnet-sample
  docs/run-keep-node.adoc
Labels: 📟 client

#3582 Support Electrum WebSocket connections
  cmd/flags.go
  cmd/flags_test.go
  config/config_test.go
  config/electrum.go
  config/electrum_test.go
  configs/config.toml.SAMPLE
  docs/resources/client-start-help
  go.mod
  go.sum
  pkg/bitcoin/electrum/config.go
  pkg/bitcoin/electrum/electrum.go
  pkg/bitcoin/electrum/electrum_integration_test.go
  pkg/bitcoin/electrum/flag.go
  pkg/bitcoin/electrum/protocol.go
  pkg/bitcoin/electrum/protocol_test.go
  test/config.json
  test/config.toml
  test/config.yaml
  test/config_flags.toml
  test/config_mixed_contracts.toml
  test/config_no_contracts.toml
  test/config_no_password.toml
Labels: 📟 client

#3593 Electrum servers list updates
  config/_electrum_urls/mainnet
  config/_electrum_urls/testnet
  config/config.go
  config/electrum.go
  config/electrum_integration_test.go
  config/electrum_test.go
  pkg/bitcoin/electrum/electrum_integration_test.go
Labels: 📟 client
