Repository keep-network/keep-core, pull requests merged in 2023-09, with the labels that each got.

#3691 Print deposit type
  cmd/maintainercli.go
  pkg/bitcoin/script.go
  pkg/maintainer/wallet/deposit_sweep.go
  pkg/maintainer/wallet/deposit_sweep_test.go
  pkg/maintainer/wallet/internal/test/marshaling.go
  pkg/maintainer/wallet/internal/test/testdata/find_deposits_scenario_0.json
  pkg/maintainer/wallet/internal/test/testdata/find_deposits_scenario_1.json
  pkg/maintainer/wallet/internal/test/testdata/find_deposits_scenario_2.json
  pkg/maintainer/wallet/internal/test/testdata/find_deposits_scenario_3.json
  pkg/maintainer/wallet/internal/test/wallettest.go
Labels: 📟 client

#3700 Set unmarshallers early during signing
  pkg/protocol/announcer/announcer.go
  pkg/protocol/announcer/announcer_test.go
  pkg/tbtc/dkg.go
  pkg/tbtc/node.go
  pkg/tbtc/signing_done.go
  pkg/tbtc/signing_done_test.go
Labels: 📟 client

#3714 Increase maintainer's redemption request amount limit to 15 BTC
  infrastructure/kube/keep-prd/keep-maintainer/kustomization.yaml
  infrastructure/kube/keep-test/keep-maintainer/kustomization.yaml
  infrastructure/kube/templates/keep-maintainer/maintainer-statefulset.yaml
Labels: :cloud: infrastructure

#3712 Support deployment of v1 contracts on Sepolia
  solidity-v1/migrations/2_deploy_contracts.js
  solidity-v1/truffle-config.js
Labels: :shipit: deployment

#3718 Use `keepnetwork/keep-client:v2.0.0-m5` for `keep-maintainer` on production
  infrastructure/kube/keep-prd/keep-maintainer/kustomization.yaml
Labels: :cloud: infrastructure

#3719 Wallet maintainer: Resolve deposit script type at the very end
  pkg/maintainer/wallet/deposit_sweep.go
Labels: 📟 client

#3706 Support deployment on Sepolia
  .github/workflows/contracts-ecdsa.yml
  .github/workflows/contracts-random-beacon.yml
  solidity/ecdsa/deploy/09_deploy_wallet_registry_governance.ts
  solidity/ecdsa/hardhat.config.ts
  solidity/random-beacon/deploy/01_deploy_reimbursement_pool.ts
  solidity/random-beacon/deploy/02_deploy_beacon_sortition_pool.ts
  solidity/random-beacon/deploy/03_deploy_beacon_dkg_validator.ts
  solidity/random-beacon/deploy/04_deploy_random_beacon.ts
  solidity/random-beacon/deploy/07_deploy_random_beacon_governance.ts
  solidity/random-beacon/deploy/09_deploy_random_beacon_chaosnet.ts
  solidity/random-beacon/hardhat.config.ts
Labels: :shipit: deployment
