Repository keep-network/keep-core, pull requests merged in 2023-06, with the labels that each got.

#3597 Client initialization order juggle
  cmd/start.go
Labels: 📟 client

#3598 Increase single DKG attempt timeout by 50 blocks
  pkg/tbtc/dkg_loop.go
  pkg/tbtc/dkg_loop_test.go
  solidity/ecdsa/contracts/WalletRegistry.sol
Labels: 📟 client

#3596 Print Electrum URL in the logs
  cmd/start.go
  config/config.go
  config/electrum.go
  scripts/install.sh
Labels: 📟 client

#3603 Update btc difficulty maintainer k8s config
  infrastructure/kube/keep-prd/btc-difficulty/kustomization.yaml
  infrastructure/kube/keep-prd/btc-difficulty/maintainer-statefulset.yaml
Labels: :cloud: infrastructure

#3604 Align keep-clients in keep-test with m3 changes
  infrastructure/kube/keep-test/keep-client/gen/template.yaml
  infrastructure/kube/keep-test/keep-client/keep-client-config.yaml
  infrastructure/kube/keep-test/keep-client/keep-clients.yaml
Labels: :cloud: infrastructure

#3571 Assemble deposit sweep proof
  pkg/bitcoin/chain_test.go
  pkg/bitcoin/spv_proof.go
  pkg/bitcoin/spv_proof_test.go
  pkg/maintainer/bitcoin_chain_test.go
Labels: 📟 client

#3620 Remove public Blockstream server from the list of auto-selected servers
  config/_electrum_urls/mainnet
  config/_electrum_urls/testnet
  config/electrum.go
  config/electrum_test.go
Labels: 📟 client

#3633 Set Node.js version to `18.15.0`
  .github/workflows/npm-ecdsa.yml
  .github/workflows/npm-random-beacon.yml
Labels: :shipit: deployment

#3618 Update dependencies to `solidity-contracts` and `random-beacon`
  solidity/ecdsa/yarn.lock
  solidity/random-beacon/yarn.lock
Labels: dependencies

#3573 Kubernetes configuration for bitcoin and electrumx
  .gitignore
  infrastructure/kube/keep-prd/.envrc
  infrastructure/kube/keep-prd/bitcoin/bitcoin-namespace.yaml
  infrastructure/kube/keep-prd/bitcoin/bitcoind/bitcoind-data-bitcoind-1-pvc.yaml
  infrastructure/kube/keep-prd/bitcoin/bitcoind/bitcoind-volumesnapshot.yaml
  infrastructure/kube/keep-prd/bitcoin/bitcoind/kustomization.yaml
  infrastructure/kube/keep-prd/bitcoin/electrumx/electrumx-compact-history-job.yaml
  infrastructure/kube/keep-prd/bitcoin/electrumx/electrumx-data-electrumx-1-pvc.yaml
  infrastructure/kube/keep-prd/bitcoin/electrumx/electrumx-data-electrumx-2-pvc.yaml
  infrastructure/kube/keep-prd/bitcoin/electrumx/electrumx-volumesnapshot.yaml
  infrastructure/kube/keep-prd/bitcoin/electrumx/kustomization.yaml
  infrastructure/kube/keep-prd/bitcoin/kustomization.yaml
  infrastructure/kube/keep-test/.envrc
  infrastructure/kube/keep-test/bitcoin/testnet/bitcoin-namespace.yaml
  infrastructure/kube/keep-test/bitcoin/testnet/bitcoind/bitcoind-data-bitcoind-1-pvc.yaml
  infrastructure/kube/keep-test/bitcoin/testnet/bitcoind/bitcoind-volumesnapshot.yaml
  infrastructure/kube/keep-test/bitcoin/testnet/bitcoind/kustomization.yaml
  infrastructure/kube/keep-test/bitcoin/testnet/electrumx/electrumx-data-electrumx-1-pvc.yaml
  infrastructure/kube/keep-test/bitcoin/testnet/electrumx/electrumx-volumesnapshot.yaml
  infrastructure/kube/keep-test/bitcoin/testnet/electrumx/kustomization.yaml
  infrastructure/kube/keep-test/bitcoin/testnet/kustomization.yaml
  infrastructure/kube/templates/bitcoin/bitcoind/.env.sample
  infrastructure/kube/templates/bitcoin/bitcoind/bitcoind-service.yaml
  infrastructure/kube/templates/bitcoin/bitcoind/bitcoind-statefulset.yaml
  infrastructure/kube/templates/bitcoin/bitcoind/bitcoind-storageclass.yaml
  infrastructure/kube/templates/bitcoin/bitcoind/bitcoind-volumesnapshotclass.yaml
  infrastructure/kube/templates/bitcoin/bitcoind/kustomization.yaml
  infrastructure/kube/templates/bitcoin/electrumx/electrumx-service.yaml
  infrastructure/kube/templates/bitcoin/electrumx/electrumx-statefulset.yaml
  infrastructure/kube/templates/bitcoin/electrumx/electrumx-storageclass.yaml
  infrastructure/kube/templates/bitcoin/electrumx/electrumx-volumesnapshotclass.yaml
  infrastructure/kube/templates/bitcoin/electrumx/kustomization.yaml
Labels: :cloud: infrastructure

#3599 Electrum integration tests for mainnet servers
  .github/workflows/client.yml
  Dockerfile
  config/electrum_integration_test.go
  internal/testdata/bitcoin/block.go
  internal/testdata/bitcoin/merkleproof.go
  internal/testdata/bitcoin/transaction.go
  pkg/bitcoin/electrum/electrum_integration_test.go
  scripts/run-integration-test.sh
Labels: 📟 client

#3630 MaintainerProxy bindings
  pkg/chain/ethereum/common/gen/Makefile
  pkg/chain/ethereum/tbtc/gen/Makefile
  pkg/chain/ethereum/tbtc/gen/_address/MaintainerProxy
  pkg/chain/ethereum/tbtc/gen/abi/MaintainerProxy.go
  pkg/chain/ethereum/tbtc/gen/cmd/MaintainerProxy.go
  pkg/chain/ethereum/tbtc/gen/contract/MaintainerProxy.go
  pkg/chain/ethereum/tbtc/gen/gen.go
Labels: 📟 client

#3634 MaintainerProxy contract handle
  cmd/flags.go
  cmd/flags_test.go
  config/config_test.go
  config/contracts.go
  pkg/chain/ethereum/tbtc.go
  test/config.json
  test/config.toml
  test/config.yaml
Labels: 📟 client

#3605 CLI for submitting deposit sweep proof
  cmd/coordinator.go
  docs/resources/client-start-help
  pkg/chain/ethereum/tbtc.go
  pkg/maintainer/spv/chain.go
  pkg/maintainer/spv/deposit_sweep_proof.go
  pkg/tbtc/chain.go
Labels: 📟 client

#3645 Add an extra 20% gas to the sweep SPV proof transaction
  pkg/chain/ethereum/tbtc.go
Labels: 📟 client

#3637 Adding Ethereum latest block number diagnostic
  cmd/start.go
  pkg/clientinfo/diagnostics.go
Labels: 📟 client

#3639 Redemption prototype: Observe incoming proposals
  pkg/bitcoin/bitcoin.go
  pkg/bitcoin/bitcoin_test.go
  pkg/bitcoin/script.go
  pkg/bitcoin/script_test.go
  pkg/bitcoin/transaction.go
  pkg/chain/ethereum/tbtc.go
  pkg/chain/ethereum/tbtc/gen/abi/WalletCoordinator.go
  pkg/chain/ethereum/tbtc/gen/cmd/WalletCoordinator.go
  pkg/chain/ethereum/tbtc/gen/contract/WalletCoordinator.go
  pkg/coordinator/tbtc_chain_test.go
  pkg/maintainer/wallet/local_chain_test.go
  pkg/tbtc/chain.go
  pkg/tbtc/chain_test.go
  pkg/tbtc/deduplicator.go
  pkg/tbtc/deduplicator_test.go
  pkg/tbtc/node.go
  pkg/tbtc/redemption.go
  pkg/tbtc/tbtc.go
Labels: 📟 client

#3647 Redemption prototype: Validate proposal and broadcast Bitcoin transaction
  pkg/bitcoin/bitcoin.go
  pkg/bitcoin/bitcoin_test.go
  pkg/bitcoin/script.go
  pkg/bitcoin/script_test.go
  pkg/chain/ethereum/tbtc.go
  pkg/chain/ethereum/tbtc_test.go
  pkg/coordinator/tbtc_chain_test.go
  pkg/maintainer/wallet/local_chain_test.go
  pkg/tbtc/chain.go
  pkg/tbtc/chain_test.go
  pkg/tbtc/deposit_sweep.go
  pkg/tbtc/deposit_sweep_test.go
  pkg/tbtc/node.go
  pkg/tbtc/redemption.go
  pkg/tbtc/redemption_test.go
  pkg/tbtc/wallet.go
  pkg/tbtc/wallet_test.go
Labels: 📟 client

#3606 Update Staticcheck action to v1.3.0
  .github/workflows/client.yml
Labels: :shipit: deployment

#3646 Enable launching of SPV maintainer
  cmd/flags.go
  cmd/flags_test.go
  cmd/maintainer.go
  config/config_test.go
  pkg/maintainer/config.go
  pkg/maintainer/maintainer.go
  pkg/maintainer/spv/config.go
  pkg/maintainer/spv/spv.go
  test/config.json
  test/config.toml
  test/config.yaml
Labels: 📟 client

#3640 Propose redemptions coordinator with CLI command
  cmd/coordinator.go
  pkg/chain/ethereum/tbtc.go
  pkg/coordinator/chain.go
  pkg/coordinator/redemptions.go
  pkg/coordinator/tbtc_chain_test.go
  pkg/maintainer/wallet/local_chain_test.go
  pkg/tbtc/chain.go
Labels: 📟 client

#3648 Adding metric and diagnostics for the Bitcoin chain
  cmd/start.go
  pkg/clientinfo/clientinfo.go
  pkg/clientinfo/diagnostics.go
  pkg/clientinfo/metrics.go
Labels: 📟 client

#3534 Automatically generate contracts documentation
  .github/workflows/contracts-ecdsa-docs.yml
  .github/workflows/contracts-random-beacon-docs.yml
  solidity/ecdsa/.prettierignore
  solidity/ecdsa/docgen-templates/common.hbs
  solidity/ecdsa/hardhat.config.ts
  solidity/ecdsa/package.json
  solidity/ecdsa/yarn.lock
  solidity/random-beacon/.prettierignore
  solidity/random-beacon/docgen-templates/common.hbs
  solidity/random-beacon/hardhat.config.ts
  solidity/random-beacon/package.json
  solidity/random-beacon/yarn.lock
Labels: :book: documentation

#3655 Use the path filter when triggering `contracts-docs-publish-preview`
  .github/workflows/contracts-ecdsa-docs.yml
  .github/workflows/contracts-random-beacon-docs.yml
Labels: :book: documentation

#3654 Modified retrieval of deposit request data
  pkg/chain/ethereum/tbtc.go
  pkg/coordinator/chain.go
  pkg/coordinator/chain_test.go
  pkg/coordinator/deposits.go
  pkg/maintainer/spv/chain.go
  pkg/maintainer/spv/deposit_sweep_proof.go
  pkg/maintainer/wallet/chain_test.go
Labels: 📟 client

#3651 Estimate redemption transaction fee during proposal
  cmd/coordinator.go
  pkg/bitcoin/script.go
  pkg/bitcoin/script_test.go
  pkg/coordinator/redemptions.go
  pkg/coordinator/redemptions_test.go
Labels: 📟 client

#3657 Split contracts API doc into multiple files
  .github/workflows/contracts-ecdsa-docs.yml
  .github/workflows/contracts-random-beacon-docs.yml
  solidity/ecdsa/hardhat.config.ts
  solidity/random-beacon/hardhat.config.ts
Labels: :book: documentation

#3659 Remove `pkg/coordinator` package
  cmd/coordinator.go
  cmd/flags.go
  cmd/flags_test.go
  config/config_test.go
  pkg/chain/ethereum/tbtc.go
  pkg/coordinator/chain.go
  pkg/coordinator/chain_test.go
  pkg/coordinator/coordinator.go
  pkg/coordinator/deposits.go
  pkg/coordinator/deposits_test.go
  pkg/coordinator/sweep.go
  pkg/coordinator/sweep_test.go
  pkg/maintainer/wallet/bitcoin_chain_test.go
  pkg/maintainer/wallet/chain.go
  pkg/maintainer/wallet/chain_test.go
  pkg/maintainer/wallet/config.go
  pkg/maintainer/wallet/deposit_sweep.go
  pkg/maintainer/wallet/deposit_sweep_test.go
  pkg/maintainer/wallet/internal/test/marshaling.go
  pkg/maintainer/wallet/internal/test/testdata/find_deposits_scenario_0.json
  pkg/maintainer/wallet/internal/test/testdata/find_deposits_scenario_1.json
  pkg/maintainer/wallet/internal/test/testdata/find_deposits_scenario_2.json
  pkg/maintainer/wallet/internal/test/testdata/find_deposits_scenario_3.json
  pkg/maintainer/wallet/internal/test/testdata/propose_sweep_scenario_0.json
  pkg/maintainer/wallet/internal/test/testdata/propose_sweep_scenario_1.json
  pkg/maintainer/wallet/internal/test/testdata/propose_sweep_scenario_2.json
  pkg/maintainer/wallet/internal/test/wallettest.go
  pkg/maintainer/wallet/redemptions.go
  pkg/maintainer/wallet/redemptions_test.go
  pkg/maintainer/wallet/sweep.go
  pkg/maintainer/wallet/wallet.go
  pkg/maintainer/wallet/wallet_test.go
  pkg/tbtc/chain.go
  test/config.json
  test/config.toml
  test/config.yaml
Labels: 📟 client

#3658 Block header structure update
  pkg/bitcoin/block.go
  pkg/bitcoin/block_test.go
Labels: 📟 client

#3660 Invoke automated redemptions periodically by maintainer
  pkg/maintainer/wallet/redemptions.go
  pkg/maintainer/wallet/wallet.go
Labels: 📟 client
