Repository keep-network/keep-core, pull requests merged in 2024-01, with the labels that each got.

#3760 Compilation error fix due to duplicated generated types
  pkg/chain/ethereum/tbtc/gen/Makefile
  pkg/chain/ethereum/tbtc/gen/abi/WalletProposalValidator.go
  pkg/chain/ethereum/tbtc/gen/cmd/WalletProposalValidator.go
  pkg/chain/ethereum/tbtc/gen/contract/WalletProposalValidator.go
Labels: 📟 client

#3762 SPV maintainer: Add coinbase data to submitted SPV proofs
  internal/testdata/bitcoin/block.go
  pkg/bitcoin/chain.go
  pkg/bitcoin/chain_test.go
  pkg/bitcoin/electrum/electrum.go
  pkg/bitcoin/electrum/electrum_integration_test.go
  pkg/bitcoin/spv_proof.go
  pkg/bitcoin/spv_proof_test.go
  pkg/chain/ethereum/tbtc.go
  pkg/chain/ethereum/tbtc/gen/abi/Bridge.go
  pkg/chain/ethereum/tbtc/gen/abi/MaintainerProxy.go
  pkg/chain/ethereum/tbtc/gen/cmd/Bridge.go
  pkg/chain/ethereum/tbtc/gen/contract/Bridge.go
  pkg/maintainer/btcdiff/bitcoin_chain_test.go
  pkg/maintainer/spv/bitcoin_chain_test.go
  pkg/tbtc/bitcoin_chain_test.go
  pkg/tbtcpg/bitcoin_chain_test.go
Labels: 📟 client

#3765 Sweep deposits with extra data
  pkg/chain/ethereum/tbtc.go
  pkg/tbtc/chain.go
  pkg/tbtc/chain_test.go
  pkg/tbtc/deposit.go
  pkg/tbtc/deposit_sweep.go
  pkg/tbtc/deposit_sweep_test.go
  pkg/tbtc/deposit_test.go
  pkg/tbtc/internal/test/marshaling.go
  pkg/tbtc/internal/test/tbtctest.go
  pkg/tbtc/internal/test/testdata/deposit_sweep_scenario_4.json
  pkg/tbtcpg/deposit_sweep_test.go
Labels: 📟 client

#3766 Include extra data of deposits for sweep fee estimation
  pkg/tbtcpg/deposit_sweep.go
  pkg/tbtcpg/internal/test/testdata/propose_sweep_scenario_0.json
Labels: 📟 client

#3746 Remove support for Goerli testnet
  .github/workflows/contracts-ecdsa.yml
  .github/workflows/contracts-random-beacon.yml
  solidity-v1/truffle-config.js
  solidity/ecdsa/deploy/09_deploy_wallet_registry_governance.ts
  solidity/ecdsa/hardhat.config.ts
  solidity/random-beacon/hardhat.config.ts
Labels: :shipit: deployment

#3768 Implement Wallet Connect v2
  solidity-v1/dashboard/.env
  solidity-v1/dashboard/craco.config.js
  solidity-v1/dashboard/package-lock.json
  solidity-v1/dashboard/package.json
  solidity-v1/dashboard/src/App.js
  solidity-v1/dashboard/src/components/CurrentWalletIconTooltip.jsx
  solidity-v1/dashboard/src/components/WalletOptions.jsx
  solidity-v1/dashboard/src/components/Web3ContextProvider.jsx
  solidity-v1/dashboard/src/connectors/index.js
  solidity-v1/dashboard/src/connectors/wallet-connect-v2.js
  solidity-v1/dashboard/src/contracts.js
  solidity-v1/dashboard/src/css/commons.less
  solidity-v1/dashboard/src/css/modal.less
  solidity-v1/dashboard/src/hooks/subscribtions/index.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToCopyStakeEvents.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToCovPoolsAuctionClosedEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToCovPoolsAuctionCreatedEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToCovPoolsWithdrawalCompletedEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToCovPoolsWithdrawalInitiatedEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToDepositWithdrawEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToDepositedEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToECDSARewardsClaimedEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToERC20TransferEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToOperatorUndelegatedEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToRecoveredStakeEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToStakedEvents.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToThresholdStakeKeepEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToTokenGrantWithdrawnEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToTopUpCompletedEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToTopUpInitiatedEvent.js
  solidity-v1/dashboard/src/hooks/subscribtions/useSubscribeToUndelegatedEvents.js
  solidity-v1/dashboard/src/hooks/useSubscribeToExplorerModeContractEvent.js
  solidity-v1/dashboard/src/lib/keep/constants/index.js
  solidity-v1/dashboard/src/lib/keep/constants/oldTokenStaking.js
  solidity-v1/dashboard/src/lib/keep/index.js
  solidity-v1/dashboard/src/pages/OverviewPage.jsx
  solidity-v1/dashboard/src/sagas/copy-stake.js
  solidity-v1/dashboard/src/sagas/index.js
Labels: :old_key: token dashboard
